import Link from 'next/link';
import {BookOpen,CheckCircle2,Headphones,Search,ShieldCheck,Sparkles,ArrowRight} from 'lucide-react';
import {isLocale,type Locale} from '@/lib/i18n';
import {notFound} from 'next/navigation';
import {collections,suttas,suttaAudio} from '@/lib/data';

export const revalidate=3600;
const coverByCollection:Record<string,string>={DN:'/visuals/nikaya/dn-book.svg',MN:'/visuals/nikaya/mn-book.svg',SN:'/visuals/nikaya/sn-book.svg',AN:'/visuals/nikaya/an-book.svg',KN:'/visuals/nikaya/kn-book.svg'};
const publicStatus:Record<string,{noteVi:string;noteEn:string;state:'ready'|'growing'}>={
  DN:{state:'ready',noteVi:'Đã có 34 bài để đọc toàn văn; thư viện đang chuẩn bị thêm các gói PDF và audio trọn bộ để nghe offline.',noteEn:'All 34 discourses are available to read; whole-collection PDF and offline audio packages are being prepared.'},
  MN:{state:'ready',noteVi:'Đủ 152 bài trong danh mục và đã có audio từng bài. Toàn văn tiếng Việt đang được đồng bộ vào bản công khai.',noteEn:'All 152 discourses are cataloged with per-discourse audio. Vietnamese full text is being synchronized into the public library.'},
  SN:{state:'growing',noteVi:'Đã xác định đầy đủ cấu trúc 56 Tương ưng; toàn văn đang được bổ sung liên tục theo nguồn đã kiểm tra.',noteEn:'The full 56-saṁyutta structure is mapped and verified full text is being added continuously.'},
  AN:{state:'growing',noteVi:'Đã xác định 1.408 mục kinh theo cấu trúc chuẩn; nội dung tiếng Việt đang được tích hợp và kiểm tra.',noteEn:'1,408 canonical entries have been mapped; Vietnamese content is being integrated and verified.'},
  KN:{state:'growing',noteVi:'Đang chuẩn hóa cấu trúc nhiều tập của Tiểu Bộ để tránh gộp hoặc tách sai các tác phẩm.',noteEn:'The multi-work Minor Collection structure is being normalized carefully to avoid incorrect grouping or splitting.'},
};

export default async function ProgressPage({params}:{params:Promise<{locale:string}>}){
  const {locale:raw}=await params;if(!isLocale(raw))notFound();const locale=raw as Locale;const vi=locale==='vi';
  const audioReady=suttas.filter(s=>Boolean(suttaAudio(s,locale))).length;
  const catalogReady=suttas.length;

  return <main className="progressPage"><div className="shell progressShell">
    <section className="progressHero" style={{alignItems:'stretch'}}>
      <div style={{maxWidth:820}}><span className="eyebrow">{vi?'DỰ ÁN 5 ĐẠI TẠNG KINH':'FIVE NIKĀYA LIBRARY PROJECT'}</span><h1>{vi?'Một thư viện Nikāya để đọc, nghe và lưu giữ lâu dài':'A Nikāya library for reading, listening and long-term preservation'}</h1><p>{vi?'Thư viện đang đưa năm bộ kinh Nikāya vào một nơi dễ sử dụng trên điện thoại và máy tính: đọc toàn văn, nghe audio, tìm kiếm và tải tài liệu để dùng offline. Nội dung được bổ sung theo nguồn đã kiểm tra; phần chưa đủ dữ liệu sẽ được ghi rõ thay vì trình bày như đã hoàn tất.':'The library brings the five Nikāya collections into one accessible place for reading, listening, searching and offline downloads. Material is added from verified sources, and incomplete areas are clearly marked.'}</p><div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:20}}><Link className="btn btnPrimary" href={`/${locale}#library`}><Search size={17}/>{vi?'Tìm bài kinh':'Search the library'}</Link><Link className="btn btnGhost" href={`/${locale}#featured`}><Headphones size={17}/>{vi?'Nghe kinh':'Listen'}</Link></div></div>
      <div style={{minWidth:260,display:'grid',gridTemplateColumns:'1fr 1fr',gap:10,alignContent:'center'}}><div style={{padding:18,border:'1px solid var(--line)',borderRadius:18,background:'var(--surface)'}}><strong style={{fontSize:28,display:'block'}}>{catalogReady.toLocaleString(vi?'vi-VN':'en-US')}</strong><span style={{fontSize:12,color:'var(--muted)'}}>{vi?'mục kinh đang có trong thư viện':'catalog entries'}</span></div><div style={{padding:18,border:'1px solid var(--line)',borderRadius:18,background:'var(--surface)'}}><strong style={{fontSize:28,display:'block'}}>{audioReady.toLocaleString(vi?'vi-VN':'en-US')}</strong><span style={{fontSize:12,color:'var(--muted)'}}>{vi?'bài hiện có audio':'entries with audio'}</span></div></div>
    </section>

    <section className="section progressCollections" style={{paddingTop:20}}><div className="sectionHead"><div><span className="sectionLabel">01</span><h2>{vi?'Năm bộ kinh trong thư viện':'The five collections'}</h2><p>{vi?'Bấm vào từng bộ để mở đúng danh sách bài kinh của bộ đó.':'Choose a collection to open its own scripture list.'}</p></div></div>
      <div className="progressCollectionGrid">{collections.map(c=>{const st=publicStatus[c.code];return <Link href={`/${locale}?collection=${c.code}#library`} className={`progressCollectionCard ${c.accent}`} key={c.code}><div className="progressCollectionArt" style={{backgroundImage:`url(${coverByCollection[c.code]})`}}/><div className="progressCollectionBody"><div className="progressCollectionTop"><span>{vi?c.viCode:c.code}</span><strong>{c.count}</strong></div><h3>{vi?c.vi:c.en}</h3><p className="pali">{c.pali}</p><p>{st?.[vi?'noteVi':'noteEn']}</p><div className={`progressState ${st?.state}`} >{st?.state==='ready'?<CheckCircle2 size={16}/>:<Sparkles size={16}/>}<span>{st?.state==='ready'?(vi?'Đã có thể sử dụng':'Available now'):(vi?'Đang tiếp tục bổ sung':'Growing continuously')}</span></div><span className="progressOpen">{vi?'Mở bộ kinh':'Open collection'} <ArrowRight size={16}/></span></div></Link>})}</div>
    </section>

    <section className="section" style={{paddingTop:14}}><div className="sectionHead"><div><span className="sectionLabel">02</span><h2>{vi?'Bạn có thể làm gì ngay bây giờ?':'What can you do right now?'}</h2></div></div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(220px,1fr))',gap:12}}>{[{icon:<BookOpen size={20}/>,t:vi?'Đọc toàn văn':'Read full text',d:vi?'Mở bài kinh trực tiếp trên web với giao diện tập trung cho việc đọc lâu.':'Open discourses directly in a focused reader.'},{icon:<Headphones size={20}/>,t:vi?'Nghe audio':'Listen to audio',d:vi?'Nghe MP3, đổi tốc độ và tải bản có sẵn để nghe offline.':'Play MP3, change speed and download available audio for offline listening.'},{icon:<Search size={20}/>,t:vi?'Tìm và lọc':'Search and filter',d:vi?'Tìm theo mã kinh, tên Việt, Pāli, bộ kinh hoặc chủ đề.':'Search by reference, title, Pāli, collection or topic.'},{icon:<ShieldCheck size={20}/>,t:vi?'Đối chiếu nguồn':'Verify sources',d:vi?'Thông tin nguồn được giữ riêng, rõ ràng để kiểm tra khi cần mà không làm rối phần kinh văn.':'Source information remains available for verification without cluttering the scripture text.'}].map(x=><article key={x.t} style={{padding:20,border:'1px solid var(--line)',borderRadius:20,background:'var(--surface)'}}><div style={{width:42,height:42,borderRadius:13,display:'grid',placeItems:'center',background:'var(--surface-2)',color:'var(--brand)',marginBottom:14}}>{x.icon}</div><h3 style={{margin:'0 0 7px',fontSize:18}}>{x.t}</h3><p style={{margin:0,color:'var(--muted)',lineHeight:1.6,fontSize:13}}>{x.d}</p></article>)}</div></section>

    <section style={{margin:'18px 0 38px',padding:24,border:'1px solid #d7ded9',borderRadius:22,background:'#f2f7f4'}}><div style={{display:'flex',gap:12,alignItems:'flex-start'}}><ShieldCheck size={23} style={{flex:'0 0 auto',marginTop:2,color:'var(--brand)'}}/><div><strong style={{fontSize:17}}>{vi?'Nguyên tắc của thư viện':'Library principle'}</strong><p style={{margin:'7px 0 0',lineHeight:1.7,color:'var(--muted)'}}>{vi?'Ưu tiên bản kinh có nguồn rõ ràng và giữ nguyên cấu trúc kinh điển. Phần nào chưa có bản Việt đáng tin cậy sẽ được ghi là chưa có, thay vì dùng AI tạo nội dung rồi trình bày như kinh văn gốc.':'The library prioritizes traceable sources and canonical structure. When a trustworthy translation is unavailable, it is marked as unavailable rather than generated and presented as scripture.'}</p></div></div></section>
    <Link className="backProgress" href={`/${locale}`}>{vi?'← Về trang chủ':'← Back home'}</Link>
  </div></main>;
}
