'use client';
import {useEffect,useMemo,useRef,useState} from 'react';
import {ChevronDown,Pause,Play,RotateCcw,Square,Volume2} from 'lucide-react';

const localeVoice:Record<string,string>={vi:'vi-VN',en:'en-US',zh:'zh-CN',hi:'hi-IN',es:'es-ES',ar:'ar',fr:'fr-FR',bn:'bn',pt:'pt-BR',ru:'ru-RU',id:'id-ID',ur:'ur',de:'de-DE',ja:'ja-JP',ko:'ko-KR',th:'th-TH',my:'my-MM',si:'si-LK',km:'km-KH',lo:'lo-LA'};
type ReaderState='idle'|'speaking'|'paused';
const labels:Record<string,{title:string;device:string;available:string;pause:string;resume:string;use:string;stop:string;restart:string;voice:string;speed:string}>={
 vi:{title:'Đọc bằng giọng có sẵn trên thiết bị',device:'Đọc bằng máy',available:'Chỉ hiện khi máy hỗ trợ',pause:'Tạm dừng',resume:'Đọc tiếp',use:'Nghe bằng máy',stop:'Dừng',restart:'Đọc lại',voice:'Giọng',speed:'Tốc độ'},en:{title:'Read with a voice installed on this device',device:'Device voice',available:'Available on this device',pause:'Pause',resume:'Resume',use:'Use device voice',stop:'Stop',restart:'Restart',voice:'Voice',speed:'Speed'},
 th:{title:'อ่านด้วยเสียงที่ติดตั้งในอุปกรณ์',device:'เสียงจากอุปกรณ์',available:'แสดงเมื่ออุปกรณ์รองรับ',pause:'หยุดชั่วคราว',resume:'อ่านต่อ',use:'ฟังด้วยอุปกรณ์',stop:'หยุด',restart:'เริ่มใหม่',voice:'เสียง',speed:'ความเร็ว'},my:{title:'စက်တွင်ရှိသော အသံဖြင့် ဖတ်ရန်',device:'စက်အသံ',available:'စက်က ပံ့ပိုးမှသာ ပြသည်',pause:'ခဏရပ်',resume:'ဆက်ဖတ်',use:'စက်အသံဖြင့် နားထောင်',stop:'ရပ်',restart:'ပြန်စ',voice:'အသံ',speed:'အမြန်နှုန်း'},
 si:{title:'උපාංගයේ ඇති හඬකින් කියවන්න',device:'උපාංග හඬ',available:'උපාංගය සහාය දක්වන විට පමණි',pause:'විරාමය',resume:'දිගටම',use:'උපාංග හඬ භාවිත කරන්න',stop:'නවත්වන්න',restart:'නැවත අරඹන්න',voice:'හඬ',speed:'වේගය'},km:{title:'អានដោយសំឡេងដែលមានលើឧបករណ៍',device:'សំឡេងឧបករណ៍',available:'បង្ហាញពេលឧបករណ៍គាំទ្រ',pause:'ផ្អាក',resume:'បន្ត',use:'ស្តាប់ដោយឧបករណ៍',stop:'ឈប់',restart:'ចាប់ផ្តើមឡើងវិញ',voice:'សំឡេង',speed:'ល្បឿន'},
 lo:{title:'ອ່ານດ້ວຍສຽງທີ່ມີໃນອຸປະກອນ',device:'ສຽງຈາກອຸປະກອນ',available:'ສະແດງເມື່ອອຸປະກອນຮອງຮັບ',pause:'ຢຸດຊົ່ວຄາວ',resume:'ອ່ານຕໍ່',use:'ຟັງດ້ວຍອຸປະກອນ',stop:'ຢຸດ',restart:'ເລີ່ມໃໝ່',voice:'ສຽງ',speed:'ຄວາມໄວ'},zh:{title:'使用设备已安装的语音朗读',device:'设备语音',available:'仅在设备支持时显示',pause:'暂停',resume:'继续',use:'使用设备语音',stop:'停止',restart:'重新开始',voice:'语音',speed:'速度'}
};

function prepare(text:string,vi:boolean){let value=text.normalize('NFC').replace(/\u00a0/g,' ').replace(/[–—]/g,', ').replace(/\s+/g,' ').trim();if(vi)value=value.replace(/\bSC\s*(\d+)\b/gi,'Đoạn $1.').replace(/\bTB\s*(\d+)\b/g,'Trung Bộ $1').replace(/\bMN\s*(\d+)\b/gi,'M N $1');return value;}
function chunks(text:string,vi:boolean,max=220){const input=prepare(text,vi);if(!input)return[];const out:string[]=[];let current='';for(const sentence of input.split(/(?<=[.!?。！？])\s+/)){const s=sentence.trim();if(!s)continue;if((current+' '+s).trim().length<=max){current=(current+' '+s).trim();continue;}if(current)out.push(current);current='';if(s.length<=max){current=s;continue;}let rest=s;while(rest.length>max){let cut=rest.lastIndexOf(' ',max);if(cut<max*.55)cut=max;out.push(rest.slice(0,cut).trim());rest=rest.slice(cut).trim();}current=rest;}if(current)out.push(current);return out;}

export default function BrowserReader({text,locale,uiLocale}:{text:string;locale:string;uiLocale?:string}){
  const vi=locale==='vi';const copy=labels[uiLocale||locale]||labels.en;const queue=useMemo(()=>chunks(text,vi),[text,vi]);const [ready,setReady]=useState(false);const [voices,setVoices]=useState<SpeechSynthesisVoice[]>([]);const [voiceUri,setVoiceUri]=useState('');const [rate,setRate]=useState(1);const [state,setState]=useState<ReaderState>('idle');const indexRef=useRef(0);const activeRef=useRef(false);const utteranceRef=useRef<SpeechSynthesisUtterance|null>(null);
  useEffect(()=>{if(!('speechSynthesis' in window)||!('SpeechSynthesisUtterance' in window)){setReady(true);return;}const synth=window.speechSynthesis;const wanted=(localeVoice[locale]||locale).toLowerCase().replace('_','-');const base=wanted.split('-')[0];const load=()=>{const matching=synth.getVoices().filter(v=>v.lang.toLowerCase().replace('_','-').startsWith(base));setVoices(matching);setVoiceUri(old=>old&&matching.some(v=>v.voiceURI===old)?old:(matching.find(v=>v.lang.toLowerCase().replace('_','-')===wanted)||matching[0])?.voiceURI||'');};load();const timers=[200,800,1800,3000].map(ms=>setTimeout(()=>{load();if(ms===3000)setReady(true);},ms));const changed=()=>{load();setReady(true);};synth.addEventListener?.('voiceschanged',changed);return()=>{timers.forEach(clearTimeout);synth.removeEventListener?.('voiceschanged',changed);activeRef.current=false;synth.cancel();};},[locale]);
  function finish(){activeRef.current=false;utteranceRef.current=null;indexRef.current=0;setState('idle');}
  function speak(index:number){if(!activeRef.current||index>=queue.length){finish();return;}const synth=window.speechSynthesis;const live=synth.getVoices();const selected=live.find(v=>v.voiceURI===voiceUri)||voices[0];if(!selected){finish();return;}const u=new SpeechSynthesisUtterance(queue[index]);u.voice=selected;u.lang=localeVoice[locale]||locale;u.rate=rate;u.pitch=1;u.volume=1;utteranceRef.current=u;u.onstart=()=>setState('speaking');u.onend=()=>{if(activeRef.current){indexRef.current=index+1;setTimeout(()=>speak(index+1),80);}};u.onerror=(e:any)=>{if(e?.error!=='canceled'&&e?.error!=='interrupted')finish();};synth.speak(u);}
  function start(){if(!queue.length||!voiceUri)return;window.speechSynthesis.cancel();activeRef.current=true;indexRef.current=0;speak(0);}function toggle(){const synth=window.speechSynthesis;if(state==='speaking'){synth.pause();setState('paused');return;}if(state==='paused'){synth.resume();setState('speaking');return;}start();}function stop(){activeRef.current=false;window.speechSynthesis.cancel();utteranceRef.current=null;indexRef.current=0;setState('idle');}function restart(){stop();setTimeout(start,80);}
  if(!ready||!voices.length||!voiceUri)return null;
  return <details className="essentialDisclosure listenDisclosure deviceSpeechDisclosure" id="device-speech"><summary title={copy.title}><span className="miniActionIcon"><Volume2 size={17}/></span><span><strong>{copy.device}</strong><small>{copy.available}</small></span><ChevronDown size={15} className="disclosureChevron"/></summary><div className="disclosureBody"><div className="browserReader compactTts deviceOnlyTts"><div className="ttsPrimary"><button className="ttsMain" onClick={toggle}>{state==='speaking'?<Pause size={17}/>:<Play size={17} fill="currentColor"/>}{state==='speaking'?copy.pause:state==='paused'?copy.resume:copy.use}</button><button className="ttsIcon" onClick={stop} title={copy.stop}><Square size={16}/></button><button className="ttsIcon" onClick={restart} title={copy.restart}><RotateCcw size={16}/></button></div><div className="ttsControls"><label><span>{copy.voice}</span><select value={voiceUri} onChange={e=>setVoiceUri(e.target.value)}>{voices.map(v=><option value={v.voiceURI} key={v.voiceURI}>{v.name} · {v.lang}</option>)}</select></label><label><span>{copy.speed}</span><select value={rate} onChange={e=>setRate(Number(e.target.value))}>{[.8,.9,1,1.1,1.25,1.5].map(v=><option value={v} key={v}>{v}×</option>)}</select></label></div></div></div></details>;
}
