'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {BookOpen,Headphones,Search,SlidersHorizontal,Clock,ArrowUpRight} from 'lucide-react';
import {collections,suttas,suttaDisplayCode,suttaAudio} from '@/lib/data';
import type {Locale} from '@/lib/i18n';
import {publicUi} from '@/lib/public-ui';

const PAGE_SIZE=60;
const l:Record<string,{all:string;audio:string;allCollections:string;results:string;showing:string;status:string;statusNote:string;read:string;none:string;noneBody:string;more:string;min:string}>={
vi:{all:'Đọc tất cả',audio:'Có audio',allCollections:'Tất cả 5 bộ',results:'bài đang mở để đọc',showing:'đang hiện',status:'Tình trạng bộ kinh',statusNote:'Thư viện chỉ hiển thị kinh văn đã có nguồn đối chiếu. Những phần chưa đủ nguồn được giữ minh bạch trong hàng chờ thay vì tự tạo nội dung.',read:'Đọc',none:'Chưa thấy bài phù hợp',noneBody:'Thử tên kinh, mã số, một từ Pāli hoặc chủ đề rộng hơn.',more:'Xem thêm',min:'phút'},
en:{all:'All reading',audio:'With audio',allCollections:'All five Nikāyas',results:'discourses ready to open',showing:'showing',status:'Collection status',statusNote:'Only source-backed scripture is shown. Missing source material remains transparently queued rather than being generated.',read:'Read',none:'No matching discourse yet',noneBody:'Try a title, code, Pāli word, or a broader topic.',more:'Show more',min:'min'},
th:{all:'อ่านทั้งหมด',audio:'มีเสียง',allCollections:'นิกายทั้ง 5',results:'รายการพร้อมอ่าน',showing:'กำลังแสดง',status:'สถานะนิกาย',statusNote:'แสดงเฉพาะพระสูตรที่มีแหล่งตรวจสอบได้ ส่วนที่ยังขาดแหล่งจะอยู่ในคิวอย่างโปร่งใสและไม่สร้างข้อความขึ้นเอง',read:'อ่าน',none:'ไม่พบพระสูตรที่ตรงกัน',noneBody:'ลองชื่อ รหัส คำบาลี หรือหัวข้อที่กว้างขึ้น',more:'แสดงเพิ่ม',min:'นาที'},
my:{all:'အားလုံးဖတ်ရန်',audio:'အသံပါရှိ',allCollections:'နိကာယ် ၅ ရပ်လုံး',results:'ဖတ်ရှုရန် ရရှိသော ကျမ်းစာများ',showing:'ပြထားသည်',status:'နိကာယ် အခြေအနေ',statusNote:'ရင်းမြစ်စစ်ဆေးနိုင်သော ကျမ်းစာကိုသာ ပြသည်။ ရင်းမြစ်မပြည့်စုံသေးသော အပိုင်းများကို မဖန်တီးဘဲ စောင့်ဆိုင်းစာရင်းတွင် ထားသည်။',read:'ဖတ်ရန်',none:'ကိုက်ညီသော ကျမ်းစာ မတွေ့ပါ',noneBody:'ခေါင်းစဉ်၊ ကုဒ်၊ ပါဠိစကားလုံး သို့မဟုတ် ပိုကျယ်သော အကြောင်းအရာကို စမ်းပါ။',more:'ပိုပြရန်',min:'မိနစ်'},
si:{all:'සියල්ල කියවන්න',audio:'ශ්‍රව්‍ය සහිත',allCollections:'නිකාය පහම',results:'කියවීමට සූදානම් සුත්ත',showing:'පෙන්වන්නේ',status:'නිකාය තත්ත්වය',statusNote:'සත්‍යාපනය කළ හැකි මූලාශ්‍ර සහිත ධර්ම පාඨ පමණක් පෙන්වයි. අහිමි දේ නිර්මාණය නොකර පැහැදිලිව පෝලිමේ තබයි.',read:'කියවන්න',none:'ගැලපෙන සුත්තක් නැත',noneBody:'මාතෘකාව, කේතය, පාලි වචනයක් හෝ පුළුල් විෂයක් උත්සාහ කරන්න.',more:'තවත් පෙන්වන්න',min:'මිනිත්තු'},
km:{all:'អានទាំងអស់',audio:'មានសំឡេង',allCollections:'និកាយទាំង ៥',results:'ព្រះសូត្រដែលអាចអានបាន',showing:'កំពុងបង្ហាញ',status:'ស្ថានភាពនិកាយ',statusNote:'បង្ហាញតែគម្ពីរដែលមានប្រភពអាចផ្ទៀងផ្ទាត់បាន។ ផ្នែកខ្វះប្រភពត្រូវរក្សាក្នុងបញ្ជីរង់ចាំ មិនបង្កើតជំនួសទេ។',read:'អាន',none:'មិនមានលទ្ធផលត្រូវគ្នា',noneBody:'សាកចំណងជើង លេខកូដ ពាក្យបាលី ឬប្រធានបទទូលំទូលាយជាងនេះ។',more:'បង្ហាញបន្ថែម',min:'នាទី'},
lo:{all:'ອ່ານທັງໝົດ',audio:'ມີສຽງ',allCollections:'ນິກາຍທັງ 5',results:'ພຣະສູດທີ່ພ້ອມອ່ານ',showing:'ກຳລັງສະແດງ',status:'ສະຖານະນິກາຍ',statusNote:'ສະແດງສະເພາະພຣະສູດທີ່ມີແຫຼ່ງກວດສອບໄດ້. ສ່ວນທີ່ຂາດແຫຼ່ງຈະຢູ່ໃນຄິວໂດຍບໍ່ສ້າງຂຶ້ນໃໝ່.',read:'ອ່ານ',none:'ບໍ່ພົບພຣະສູດທີ່ກົງ',noneBody:'ລອງຊື່ ລະຫັດ ຄຳບາລີ ຫຼືຫົວຂໍ້ທີ່ກວ້າງຂຶ້ນ.',more:'ສະແດງເພີ່ມ',min:'ນາທີ'},
zh:{all:'阅读全部',audio:'有音频',allCollections:'全部五部尼柯耶',results:'篇可打开阅读',showing:'当前显示',status:'本部状态',statusNote:'只展示有可核查来源的经文。缺少可靠来源的部分会明确进入待办队列，不会自动编造补齐。',read:'阅读',none:'没有匹配的经文',noneBody:'请尝试标题、编号、巴利文词语或更宽泛的主题。',more:'显示更多',min:'分钟'}
};

export default function LibraryExplorer({locale,placeholder,initialCollection='ALL'}:{locale:Locale;placeholder:string;initialCollection?:string}){
 const vi=locale==='vi';const en=locale==='en';const x=l[locale]||l.en;const u=publicUi(locale);
 const [q,setQ]=useState('');const [collection,setCollection]=useState(initialCollection);const [format,setFormat]=useState<'ALL'|'AUDIO'>('ALL');const [visibleCount,setVisibleCount]=useState(PAGE_SIZE);
 const filtered=useMemo(()=>suttas.filter(s=>{const collectionName=collections.find(c=>c.code===s.collection);const hay=[s.code,s.viCode,s.collection,collectionName?.vi,collectionName?.en,collectionName?.pali,s.pali,s.vi,s.en,s.summaryVi,s.summaryEn,s.practiceVi,s.practiceEn,...s.topics].filter(Boolean).join(' ').toLocaleLowerCase();const hasAudio=!!suttaAudio(s,locale);return(collection==='ALL'||s.collection===collection)&&(format==='ALL'||hasAudio)&&hay.includes(q.trim().toLocaleLowerCase());}),[q,collection,format,locale]);
 useEffect(()=>setVisibleCount(PAGE_SIZE),[q,collection,format,locale]);const visible=filtered.slice(0,visibleCount);const selected=collections.find(c=>c.code===collection);
 const title=(s:(typeof suttas)[number])=>vi?s.vi:en?s.en:(s.pali||s.code);const ctitle=(c:(typeof collections)[number])=>vi?c.vi:en?c.en:c.pali;
 return <div className="explorer">
   <div className="libraryToolbar"><label className="searchBox"><Search size={20}/><input value={q} onChange={e=>setQ(e.target.value)} aria-label={u.search} placeholder={placeholder}/>{q&&<button type="button" onClick={()=>setQ('')} aria-label="clear">×</button>}</label><div className="formatFilter"><SlidersHorizontal size={17}/><button className={format==='ALL'?'activeFilter':''} onClick={()=>setFormat('ALL')}>{x.all}</button><button className={format==='AUDIO'?'activeFilter':''} onClick={()=>setFormat('AUDIO')}>{x.audio}</button></div></div>
   <div className="collectionChips"><button onClick={()=>setCollection('ALL')} className={collection==='ALL'?'activeChip':''}><strong>{x.allCollections}</strong></button>{collections.map(c=><button onClick={()=>setCollection(c.code)} className={collection===c.code?'activeChip':''} key={c.code}><strong>{ctitle(c)}</strong><small>{vi?c.viCode:c.code}</small></button>)}</div>
   <div className="resultLine"><strong>{filtered.length} {x.results}{selected?` · ${ctitle(selected)}`:''}</strong>{filtered.length>visible.length&&<span> · {x.showing} {visible.length}</span>}</div>
   {collection!=='ALL'&&<div className="emptyState" style={{marginBottom:'18px'}}><BookOpen size={22}/><h3>{x.status}</h3><p>{x.statusNote}</p></div>}
   <div className="suttaGrid">{visible.length?visible.map(s=>{const audio=suttaAudio(s,locale);const c=collections.find(z=>z.code===s.collection);const summary=vi?s.summaryVi:en?s.summaryEn:'';return <Link href={`/${locale}/library/${s.slug}`} className="suttaCard" key={s.slug}><div className="suttaCode dualCode"><strong>{suttaDisplayCode(s,vi)}</strong>{vi&&<small>{s.code}</small>}</div><div className="suttaContent"><div className="suttaMeta"><span>{c?ctitle(c):s.collection}</span>{s.readMinutes>0&&<span><Clock size={13}/>{s.readMinutes} {x.min}</span>}</div><h3>{title(s)}</h3><p className="pali">{s.pali}</p>{summary&&<p className="summary">{summary}</p>}{vi||en?<div className="topicRow">{s.topics.slice(0,3).map(t=><span key={t}>{t}</span>)}</div>:null}</div><div className="suttaActions"><span title={x.read}><BookOpen size={16}/></span>{audio&&<span title={audio.label}><Headphones size={16}/></span>}<ArrowUpRight className="openArrow" size={18}/></div></Link>}):<div className="emptyState"><Search size={26}/><h3>{x.none}</h3><p>{x.noneBody}</p></div>}</div>
   {visible.length<filtered.length&&<div className="loadMoreRow"><button type="button" className="btn btnGhost" onClick={()=>setVisibleCount(n=>n+PAGE_SIZE)}>{x.more} {Math.min(PAGE_SIZE,filtered.length-visible.length)}</button></div>}
 </div>;
}
