export type Collection = {code:string; pali:string; vi:string; en:string; count:string; descVi:string; descEn:string};
export const collections: Collection[] = [
  {code:'DN',pali:'Dīgha Nikāya',vi:'Trường Bộ Kinh',en:'Long Discourses',count:'34 suttas',descVi:'Các bài kinh dài, giàu bối cảnh và giáo lý tổng hợp.',descEn:'Long-form discourses with broad doctrinal and narrative scope.'},
  {code:'MN',pali:'Majjhima Nikāya',vi:'Trung Bộ Kinh',en:'Middle Length Discourses',count:'152 suttas',descVi:'Các bài kinh vừa, rất phù hợp để học theo từng chủ đề.',descEn:'Middle-length teachings ideal for topic-by-topic study.'},
  {code:'SN',pali:'Saṁyutta Nikāya',vi:'Tương Ưng Bộ Kinh',en:'Connected Discourses',count:'56 saṁyuttas',descVi:'Kinh được nhóm theo các chủ đề và nhân vật liên hệ.',descEn:'Discourses grouped into connected themes and persons.'},
  {code:'AN',pali:'Aṅguttara Nikāya',vi:'Tăng Chi Bộ Kinh',en:'Numerical Discourses',count:'11 nipātas',descVi:'Giáo pháp được hệ thống theo số lượng pháp.',descEn:'Teachings structured through numerical lists.'},
  {code:'KN',pali:'Khuddaka Nikāya',vi:'Tiểu Bộ Kinh',en:'Minor Collection',count:'15+ books',descVi:'Nhiều tuyển tập đa dạng như Pháp Cú, Kinh Tập, Udāna.',descEn:'A diverse collection including Dhammapada, Sutta Nipāta and Udāna.'}
];

export type Sutta = {slug:string;code:string;collection:string;pali:string;vi:string;en:string;topics:string[];sourceUrl:string;licenseNote:string;pdfUrl?:string;mp3Url?:string;youtubeId?:string;summaryVi:string;summaryEn:string};
export const suttas:Sutta[] = [
 {slug:'mn-21-kakacupama',code:'MN 21',collection:'MN',pali:'Kakacūpama Sutta',vi:'Kinh Ví Dụ Cái Cưa',en:'The Simile of the Saw',topics:['nhẫn nhục','tâm từ','lời nói'],sourceUrl:'https://suttacentral.net/mn21/en/sujato',licenseNote:'English translation: Bhikkhu Sujato, CC0. Audio recording: Roland Kitchen / PaliAudio, CC BY 4.0.',pdfUrl:'https://www.holybooks.com/wp-content/uploads/Middle-Discourses-I.pdf',mp3Url:'https://static1.squarespace.com/static/58384d438419c2f3cb695f5b/t/5c229b65032be478967ea150/1545772021948/MN%2B21%2BThe%2Bsimile%2Bof%2Bthe%2Bsaw.mp3',summaryVi:'Một bài kinh nổi tiếng về kham nhẫn, cách ứng xử với lời nói khó nghe và giữ tâm không sân hận.',summaryEn:'A foundational discourse on patience, difficult speech, and maintaining a mind free from hate.'},
 {slug:'dn-16-mahaparinibbana',code:'DN 16',collection:'DN',pali:'Mahāparinibbāna Sutta',vi:'Kinh Đại Bát Niết-bàn',en:'The Great Passing',topics:['cuối đời','chánh niệm','tăng đoàn'],sourceUrl:'https://suttacentral.net/dn16',licenseNote:'Translation rights vary by edition. Verify before redistribution.',summaryVi:'Tường thuật giai đoạn cuối đời Đức Phật với nhiều chỉ dẫn quan trọng về thực hành và cộng đồng.',summaryEn:'The Buddha’s final journey, with essential teachings on practice, community, and remembrance.'},
 {slug:'sn-56-11-dhammacakkappavattana',code:'SN 56.11',collection:'SN',pali:'Dhammacakkappavattana Sutta',vi:'Kinh Chuyển Pháp Luân',en:'Setting the Dhamma Wheel in Motion',topics:['tứ diệu đế','trung đạo','bát chánh đạo'],sourceUrl:'https://suttacentral.net/sn56.11/en/sujato',licenseNote:'English translation: Bhikkhu Sujato, CC0. Audio recording: Roland Kitchen / PaliAudio, CC BY 4.0.',mp3Url:'https://static1.squarespace.com/static/58384d438419c2f3cb695f5b/t/5a2efa1f4192022b9fc5dce6/1513028180495/%5B11%5D%2BTurning%2Bthe%2Bwheel%2Bof%2Btruth%2B-%2BMP3.mp3',summaryVi:'Bài pháp đầu tiên trình bày Trung đạo, Bốn sự thật và con đường thực hành.',summaryEn:'The first teaching on the Middle Way, Four Noble Truths, and the path of practice.'},
 {slug:'an-10-60-girimananda',code:'AN 10.60',collection:'AN',pali:'Girimānanda Sutta',vi:'Kinh Girimānanda',en:'With Girimānanda',topics:['quán tưởng','bệnh','vô thường'],sourceUrl:'https://suttacentral.net/an10.60',licenseNote:'Translation rights vary by edition. Verify before redistribution.',summaryVi:'Mười phép quán được trao truyền trong bối cảnh Tôn giả Girimānanda lâm bệnh.',summaryEn:'Ten perceptions taught in the context of Venerable Girimānanda’s illness.'},
 {slug:'snp-1-8-metta',code:'Snp 1.8',collection:'KN',pali:'Karaṇīyametta Sutta',vi:'Kinh Từ Bi',en:'The Discourse on Loving-kindness',topics:['tâm từ','thiền','đạo đức'],sourceUrl:'https://suttacentral.net/snp1.8',licenseNote:'Translation rights vary by edition. Verify before redistribution.',summaryVi:'Bài kệ ngắn, được tụng đọc rộng rãi, hướng dẫn phát triển lòng từ đến mọi loài.',summaryEn:'A concise and widely recited teaching on boundless loving-kindness for all beings.'}
];
