export type Collection={code:string;pali:string;vi:string;en:string;count:string;descVi:string;descEn:string;accent:string};

export const collections:Collection[]=[
  {code:'DN',pali:'Dīgha Nikāya',vi:'Trường Bộ',en:'Long Discourses',count:'34 bài kinh',descVi:'Các bài kinh dài, giàu bối cảnh và hệ thống giáo pháp.',descEn:'Long-form discourses with broad doctrinal and narrative scope.',accent:'amber'},
  {code:'MN',pali:'Majjhima Nikāya',vi:'Trung Bộ',en:'Middle Discourses',count:'152 bài kinh',descVi:'Các bài kinh vừa, rất phù hợp học theo từng chủ đề thực hành.',descEn:'Middle-length teachings ideal for topic-by-topic practice.',accent:'emerald'},
  {code:'SN',pali:'Saṁyutta Nikāya',vi:'Tương Ưng Bộ',en:'Connected Discourses',count:'56 tương ưng',descVi:'Các bài kinh được nhóm theo chủ đề, nhân vật và pháp môn liên hệ.',descEn:'Discourses grouped into connected themes, people and practices.',accent:'blue'},
  {code:'AN',pali:'Aṅguttara Nikāya',vi:'Tăng Chi Bộ',en:'Numbered Discourses',count:'11 chương số',descVi:'Giáo pháp được sắp theo số lượng pháp, dễ học và tra cứu.',descEn:'Teachings organized by numbered sets for quick study.',accent:'rose'},
  {code:'KN',pali:'Khuddaka Nikāya',vi:'Tiểu Bộ',en:'Minor Collection',count:'15+ tập',descVi:'Nhiều tuyển tập quan trọng như Pháp Cú, Kinh Tập và Udāna.',descEn:'A diverse collection including Dhammapada, Sutta Nipāta and Udāna.',accent:'violet'}
];

export type Sutta={
  slug:string;code:string;collection:string;pali:string;vi:string;en:string;
  topics:string[];sourceUrl:string;licenseShort:string;bookUrl?:string;mp3Url?:string;youtubeId?:string;
  summaryVi:string;summaryEn:string;practiceVi:string;practiceEn:string;readMinutes:number;featured?:boolean;
};

const MN_BOOK='https://suttacentral.net/edition/mn/en/sujato';
const DN_BOOK='https://suttacentral.net/edition/dn/en/sujato';
const SN_BOOK='https://suttacentral.net/edition/sn/en/sujato';
const AN_BOOK='https://suttacentral.net/edition/an/en/sujato';
const DHP_BOOK='https://suttacentral.net/edition/dhp/en/sujato';

export const suttas:Sutta[]=[
  {slug:'mn-21-kakacupama',code:'MN 21',collection:'MN',pali:'Kakacūpama Sutta',vi:'Kinh Ví Dụ Cái Cưa',en:'The Simile of the Saw',topics:['nhẫn nhục','tâm từ','lời nói'],sourceUrl:'https://suttacentral.net/mn21/en/sujato',licenseShort:'Bản Anh ngữ Bhikkhu Sujato · CC0',bookUrl:MN_BOOK,mp3Url:'https://static1.squarespace.com/static/58384d438419c2f3cb695f5b/t/5c229b65032be478967ea150/1545772021948/MN%2B21%2BThe%2Bsimile%2Bof%2Bthe%2Bsaw.mp3',summaryVi:'Một bài kinh nổi tiếng về kham nhẫn, cách tiếp nhận lời nói khó nghe và giữ tâm không sân hận.',summaryEn:'A foundational discourse on patience, difficult speech, and maintaining a mind free from hate.',practiceVi:'Phù hợp khi đang đối diện tranh luận, xúc phạm hoặc cảm xúc nóng giận. Hãy đọc chậm và chú ý phần Đức Phật hướng dẫn mở rộng tâm từ.',practiceEn:'Useful when facing conflict, criticism, or anger. Read slowly and notice the training in boundless goodwill.',readMinutes:18,featured:true},
  {slug:'mn-10-satipatthana',code:'MN 10',collection:'MN',pali:'Satipaṭṭhāna Sutta',vi:'Kinh Niệm Xứ',en:'Mindfulness Meditation',topics:['chánh niệm','thiền','quán thân'],sourceUrl:'https://suttacentral.net/mn10/en/sujato',licenseShort:'Bản Anh ngữ Bhikkhu Sujato · CC0',bookUrl:MN_BOOK,summaryVi:'Một trong những bài kinh nền tảng nhất về bốn niệm xứ: thân, thọ, tâm và pháp.',summaryEn:'A foundational discourse on the four establishments of mindfulness: body, feelings, mind, and principles.',practiceVi:'Dùng như bản đồ thực hành thiền. Có thể đọc theo từng phần thay vì đọc hết trong một lần.',practiceEn:'Use it as a meditation map. It works well in short sections rather than a single sitting.',readMinutes:30,featured:true},
  {slug:'mn-22-alagaddupama',code:'MN 22',collection:'MN',pali:'Alagaddūpama Sutta',vi:'Kinh Ví Dụ Con Rắn',en:'The Simile of the Snake',topics:['chấp thủ','chánh kiến','giáo pháp'],sourceUrl:'https://suttacentral.net/mn22/en/sujato',licenseShort:'Bản Anh ngữ Bhikkhu Sujato · CC0',bookUrl:MN_BOOK,summaryVi:'Bài kinh cảnh báo việc nắm giữ giáo pháp sai cách và dùng hình ảnh chiếc bè để nói về buông chấp.',summaryEn:'A discourse warning against grasping the teachings wrongly, including the famous simile of the raft.',practiceVi:'Đọc khi muốn phân biệt giữa học giáo pháp để thực hành và học để tranh thắng.',practiceEn:'Read when reflecting on the difference between practice and using teachings merely to win arguments.',readMinutes:24},
  {slug:'dn-16-mahaparinibbana',code:'DN 16',collection:'DN',pali:'Mahāparinibbāna Sutta',vi:'Kinh Đại Bát Niết-bàn',en:'The Great Passing',topics:['cuối đời','chánh niệm','tăng đoàn'],sourceUrl:'https://suttacentral.net/dn16/en/sujato',licenseShort:'Bản Anh ngữ Bhikkhu Sujato · CC0',bookUrl:DN_BOOK,summaryVi:'Tường thuật hành trình cuối đời Đức Phật với nhiều chỉ dẫn quan trọng về thực hành, cộng đồng và sự tự nương tựa.',summaryEn:'The Buddha’s final journey, with important guidance on practice, community, and self-reliance.',practiceVi:'Nên đọc theo chương. Đánh dấu các lời dạy về chánh niệm, giới luật và tinh thần tự mình thắp đuốc lên mà đi.',practiceEn:'Best read chapter by chapter, noting teachings on mindfulness, discipline, and self-reliance.',readMinutes:75,featured:true},
  {slug:'dn-31-sigalovada',code:'DN 31',collection:'DN',pali:'Siṅgāla Sutta',vi:'Kinh Giáo Thọ Thi-ca-la-việt',en:'Advice to Sigālaka',topics:['gia đình','đạo đức','đời sống'],sourceUrl:'https://suttacentral.net/dn31/en/sujato',licenseShort:'Bản Anh ngữ Bhikkhu Sujato · CC0',bookUrl:DN_BOOK,summaryVi:'Những hướng dẫn rất thực tế về quan hệ gia đình, bạn bè, công việc và trách nhiệm xã hội.',summaryEn:'Practical guidance on family, friendship, work, and social responsibilities.',practiceVi:'Rất phù hợp để đọc theo chủ đề đời sống hằng ngày và thảo luận trong gia đình.',practiceEn:'Especially useful for everyday life and family discussion.',readMinutes:22},
  {slug:'sn-56-11-dhammacakkappavattana',code:'SN 56.11',collection:'SN',pali:'Dhammacakkappavattana Sutta',vi:'Kinh Chuyển Pháp Luân',en:'Setting the Dhamma Wheel in Motion',topics:['tứ diệu đế','trung đạo','bát chánh đạo'],sourceUrl:'https://suttacentral.net/sn56.11/en/sujato',licenseShort:'Bản Anh ngữ Bhikkhu Sujato · CC0',bookUrl:SN_BOOK,mp3Url:'https://static1.squarespace.com/static/58384d438419c2f3cb695f5b/t/5a2efa1f4192022b9fc5dce6/1513028180495/%5B11%5D%2BTurning%2Bthe%2Bwheel%2Bof%2Btruth%2B-%2BMP3.mp3',summaryVi:'Bài pháp đầu tiên trình bày Trung đạo, Bốn sự thật cao quý và con đường thực hành.',summaryEn:'The first teaching on the Middle Way, Four Noble Truths, and the path of practice.',practiceVi:'Đây là điểm bắt đầu rất tốt cho người mới. Có thể nghe audio trước rồi đọc lại phần Tứ Diệu Đế.',practiceEn:'An excellent starting point. Listen first, then revisit the Four Noble Truths in the text.',readMinutes:12,featured:true},
  {slug:'sn-22-59-anattalakkhana',code:'SN 22.59',collection:'SN',pali:'Anattalakkhaṇa Sutta',vi:'Kinh Vô Ngã Tướng',en:'The Characteristic of Not-Self',topics:['vô ngã','năm uẩn','tuệ quán'],sourceUrl:'https://suttacentral.net/sn22.59/en/sujato',licenseShort:'Bản Anh ngữ Bhikkhu Sujato · CC0',bookUrl:SN_BOOK,summaryVi:'Bài kinh trọng yếu về việc quán năm uẩn là vô thường, khổ và không phải tự ngã.',summaryEn:'A key discourse on seeing the five aggregates as impermanent, stressful, and not-self.',practiceVi:'Đọc chậm từng uẩn và liên hệ trực tiếp với kinh nghiệm thân tâm hiện tại.',practiceEn:'Take one aggregate at a time and relate it to present-moment experience.',readMinutes:10},
  {slug:'an-3-65-kesamutti',code:'AN 3.65',collection:'AN',pali:'Kesamutti Sutta',vi:'Kinh Kesamutti (Kālāma)',en:'With the Kālāmas of Kesamutta',topics:['niềm tin','kiểm chứng','đạo đức'],sourceUrl:'https://suttacentral.net/an3.65/en/sujato',licenseShort:'Bản Anh ngữ Bhikkhu Sujato · CC0',bookUrl:AN_BOOK,summaryVi:'Bài kinh nổi tiếng về cách xem xét lời dạy, quan sát hậu quả và không vội tin chỉ vì truyền thống hay lời đồn.',summaryEn:'A famous discourse on evaluating teachings by their consequences rather than accepting claims uncritically.',practiceVi:'Hữu ích khi gặp nhiều quan điểm trái ngược. Tập trung vào tiêu chuẩn thiện, bất thiện và hậu quả thực tế.',practiceEn:'Useful amid conflicting claims: focus on skillful qualities and observable consequences.',readMinutes:14,featured:true},
  {slug:'an-10-60-girimananda',code:'AN 10.60',collection:'AN',pali:'Girimānanda Sutta',vi:'Kinh Girimānanda',en:'With Girimānanda',topics:['quán tưởng','bệnh','vô thường'],sourceUrl:'https://suttacentral.net/an10.60/en/sujato',licenseShort:'Bản Anh ngữ Bhikkhu Sujato · CC0',bookUrl:AN_BOOK,summaryVi:'Mười phép quán được trao truyền trong bối cảnh Tôn giả Girimānanda lâm bệnh.',summaryEn:'Ten perceptions taught in the context of Venerable Girimānanda’s illness.',practiceVi:'Có thể dùng như danh sách mười đề mục quán chiếu, mỗi lần chọn một đề mục.',practiceEn:'Use it as a list of ten contemplations, taking one theme at a time.',readMinutes:16},
  {slug:'dhp-1-20-yamakavagga',code:'Dhp 1–20',collection:'KN',pali:'Yamakavagga',vi:'Pháp Cú · Phẩm Song Yếu',en:'Dhammapada · Pairs',topics:['tâm','nghiệp','đạo đức'],sourceUrl:'https://suttacentral.net/dhp1-20/en/sujato',licenseShort:'Bản Anh ngữ Bhikkhu Sujato · CC0',bookUrl:DHP_BOOK,summaryVi:'Hai mươi câu kệ mở đầu Pháp Cú, nhấn mạnh vai trò dẫn đầu của tâm và hệ quả của hành động.',summaryEn:'The opening twenty verses of the Dhammapada, emphasizing the leading role of mind and the results of action.',practiceVi:'Phù hợp đọc mỗi ngày vài câu, lưu lại câu chạm đến mình và quay lại suy ngẫm.',practiceEn:'Ideal for a few verses each day; save a verse and return to it during the day.',readMinutes:8,featured:true},
  {slug:'snp-1-8-metta',code:'Snp 1.8',collection:'KN',pali:'Karaṇīyametta Sutta',vi:'Kinh Từ Bi',en:'The Discourse on Loving-kindness',topics:['tâm từ','thiền','đạo đức'],sourceUrl:'https://suttacentral.net/snp1.8/en/mills',licenseShort:'Bản dịch Laurence Khantipalo Mills · CC0',summaryVi:'Bài kệ ngắn, được tụng đọc rộng rãi, hướng dẫn phát triển lòng từ không giới hạn đến mọi loài.',summaryEn:'A concise and widely recited teaching on boundless loving-kindness for all beings.',practiceVi:'Rất phù hợp nghe hoặc đọc trước thời thiền, sau đó mở rộng tâm từ theo từng hướng.',practiceEn:'Well suited before meditation, gradually extending goodwill in every direction.',readMinutes:7}
];
