import type {Locale} from '@/lib/i18n';

type Kind='about'|'privacy'|'terms'|'editorial-policy';
export type InfoContent={title:string;lead:string;sections:[string,string][];transparency:string;transparencyBody:string;back:string};
type L='vi'|'en'|'th'|'my'|'si'|'km'|'lo'|'zh';

const common:Record<L,{transparency:string;body:string;back:string}>={
 vi:{transparency:'Nguyên tắc minh bạch',body:'Ưu tiên nguồn kiểm chứng được, ghi công rõ ràng và không dùng nội dung tạo sinh để thay thế kinh văn còn thiếu.',back:'Về thư viện'},
 en:{transparency:'Transparency principle',body:'Prefer verifiable sources, clear attribution and no generated text as a substitute for missing scripture.',back:'Back to library'},
 th:{transparency:'หลักความโปร่งใส',body:'ให้ความสำคัญกับแหล่งที่ตรวจสอบได้ การระบุผู้แปลอย่างชัดเจน และไม่ใช้ข้อความที่สร้างขึ้นแทนพระสูตรที่ขาดหาย',back:'กลับไปยังคลัง'},
 my:{transparency:'ပွင့်လင်းမြင်သာမှု မူဝါဒ',body:'စစ်ဆေးနိုင်သော ရင်းမြစ်၊ ရှင်းလင်းသော ဂုဏ်ပြုဖော်ပြချက်နှင့် ပျောက်နေသော ကျမ်းစာအစား AI စာသားမသုံးခြင်းကို ဦးစားပေးသည်။',back:'စာကြည့်တိုက်သို့ ပြန်ရန်'},
 si:{transparency:'විනිවිදභාවයේ මූලධර්මය',body:'සත්‍යාපනය කළ හැකි මූලාශ්‍ර, පැහැදිලි කර්තෘත්වය සහ අහිමි ධර්ම පාඨ වෙනුවට ජනනීය පාඨ නොයෙදීම ප්‍රමුඛ කරමු.',back:'පුස්තකාලයට ආපසු'},
 km:{transparency:'គោលការណ៍តម្លាភាព',body:'ផ្តល់អាទិភាពដល់ប្រភពអាចផ្ទៀងផ្ទាត់បាន ការបញ្ជាក់អ្នកបកប្រែច្បាស់លាស់ និងមិនប្រើអត្ថបទបង្កើតដោយ AI ជំនួសគម្ពីរដែលខ្វះ។',back:'ត្រឡប់ទៅបណ្ណាល័យ'},
 lo:{transparency:'ຫຼັກຄວາມໂປ່ງໃສ',body:'ໃຫ້ຄວາມສຳຄັນແກ່ແຫຼ່ງທີ່ກວດສອບໄດ້ ການລະບຸຜູ້ແປຊັດເຈນ ແລະບໍ່ໃຊ້ຂໍ້ຄວາມ AI ແທນພຣະສູດທີ່ຂາດ.',back:'ກັບຫໍສະໝຸດ'},
 zh:{transparency:'透明原则',body:'优先采用可核查来源，清楚标注译者与出处，不用生成式内容冒充缺失的经文。',back:'返回图书馆'}
};

const pages:Record<L,Record<Kind,{title:string;lead:string;sections:[string,string][]}>>={
 en:{
  about:{title:'About the library',lead:'A calm, source-conscious digital library for reading, listening to, studying and preserving the Theravāda Pāli Canon.',sections:[['What we are building','The library combines canonical catalogues, full-text reading, traceable sources, generated PDFs, audio and reading-progress tools for phones, tablets and desktop screens.'],['Our approach','We prefer identifiable editions and clearly show translators or upstream sources. Software and AI may improve accessibility and production workflows, but may not fabricate scripture.'],['Languages','Each public interface is localized. Scripture itself is shown only from a source-backed translation; when one is unavailable, any English fallback is clearly labelled.'],['Preservation','Corpus and audio assets may be mirrored across independent services for resilience while attribution and original rights remain attached.']]},
  privacy:{title:'Privacy policy',lead:'A plain-language summary of what the library stores and how optional analytics or advertising would be handled.',sections:[['Data on your device','Reading progress and saved passages may use browser storage on your own device without requiring an account.'],['Server logs','Hosting providers may process basic technical request and security information for delivery, abuse prevention and reliability.'],['Analytics and advertising','Scripture reading does not require advertising cookies. If analytics or advertising are enabled later, appropriate notices and consent controls will be provided where required.'],['External services','Links or embeds from SuttaCentral, YouTube, archives or CDN providers are governed by those services’ own privacy policies.']]},
  terms:{title:'Terms of use',lead:'Simple terms intended to keep the library open, useful and transparent.',sections:[['Educational use','The library is provided for reading, listening, study and reference.'],['Scripture rights','Source texts and translations may carry different copyright or licensing terms. Attribution and source links are preserved where available.'],['Availability','Content and infrastructure can change as sources, corrections and audio versions improve; uninterrupted availability is not guaranteed.'],['Responsible use','Do not abuse the service, bypass access controls, overload infrastructure or violate applicable law or the rights of others.']]},
  'editorial-policy':{title:'Sources & editorial policy',lead:'How scripture enters the library, how provenance is preserved and how corrections are handled.',sections:[['Source-first corpus','Scripture comes from identifiable editions or trusted repositories and keeps enough provenance for independent verification.'],['No invented scripture','AI may assist software, search, QA and audio workflows, but must never invent missing scripture or present generated prose as canonical text.'],['Language fallback','If a selected language lacks reliable full text, an English source may be shown only with an explicit fallback notice and source attribution.'],['Corrections and audio','Text remains the authority for verification. Audio can be regenerated as pronunciation or quality improves, while version and source metadata remain traceable.']]}
 },
 vi:{
  about:{title:'Giới thiệu thư viện',lead:'Thư viện số hiện đại, yên tĩnh và chú trọng nguồn gốc để đọc, nghe, nghiên cứu và lưu giữ Tam Tạng Pāli Theravāda.',sections:[['Thư viện đang xây dựng','Hệ thống kết hợp mục lục chuẩn, đọc toàn văn, nguồn đối chiếu, PDF tự tạo, audio và lưu tiến độ trên điện thoại, máy tính bảng và máy tính.'],['Nguyên tắc','Ưu tiên bản có nguồn rõ ràng, ghi người dịch và xuất xứ. Phần mềm và AI được dùng để cải thiện công cụ, không được bịa kinh văn.'],['Ngôn ngữ','Giao diện công khai được bản địa hóa. Kinh văn chỉ dùng bản dịch có nguồn; nếu phải tạm dùng tiếng Anh thì phải ghi rõ đó là fallback.'],['Bảo tồn','Dữ liệu và audio có thể được sao lưu ở nhiều nơi nhưng luôn giữ thông tin nguồn, quyền và phiên bản.']]},
  privacy:{title:'Chính sách quyền riêng tư',lead:'Giải thích ngắn gọn dữ liệu thư viện có thể lưu và cách xử lý analytics hoặc quảng cáo nếu được bật.',sections:[['Dữ liệu trên thiết bị','Tiến độ đọc và đoạn đã lưu có thể nằm trong bộ nhớ trình duyệt mà không cần tài khoản.'],['Nhật ký máy chủ','Nhà cung cấp hosting có thể xử lý dữ liệu kỹ thuật cơ bản để phân phối nội dung, chống lạm dụng và xử lý lỗi.'],['Analytics và quảng cáo','Đọc kinh không cần cookie quảng cáo. Nếu bật analytics hoặc quảng cáo về sau, thư viện sẽ công bố và xin đồng ý khi pháp luật hoặc chính sách yêu cầu.'],['Dịch vụ bên ngoài','Liên kết hoặc nội dung nhúng từ SuttaCentral, YouTube, kho lưu trữ hay CDN tuân theo chính sách riêng của các dịch vụ đó.']]},
  terms:{title:'Điều khoản sử dụng',lead:'Các điều khoản đơn giản để thư viện duy trì tính mở, hữu ích và minh bạch.',sections:[['Mục đích','Thư viện phục vụ đọc, nghe, học tập và tham khảo.'],['Quyền đối với kinh văn','Nguồn kinh và bản dịch có thể có giấy phép khác nhau; thư viện giữ ghi công và đường dẫn nguồn khi có.'],['Tính sẵn sàng','Nội dung và hạ tầng có thể thay đổi khi sửa lỗi, nguồn thay đổi hoặc audio được nâng cấp.'],['Sử dụng có trách nhiệm','Không lạm dụng dịch vụ, vượt kiểm soát truy cập, gây quá tải, phát tán mã độc hoặc vi phạm pháp luật và quyền của người khác.']]},
  'editorial-policy':{title:'Nguồn & nguyên tắc biên tập',lead:'Cách kinh văn được đưa vào thư viện, giữ xuất xứ và xử lý sửa đổi.',sections:[['Ưu tiên nguồn','Kinh văn phải đến từ bản có thể nhận diện hoặc kho dữ liệu đáng tin cậy và giữ đủ thông tin để đối chiếu.'],['Không bịa kinh','AI có thể hỗ trợ phần mềm, QA, tìm kiếm và audio nhưng không được tạo đoạn kinh còn thiếu rồi trình bày như kinh văn chính thức.'],['Fallback ngôn ngữ','Nếu chưa có toàn văn đáng tin cậy ở ngôn ngữ được chọn, bản tiếng Anh chỉ được hiển thị khi có cảnh báo rõ ràng và ghi nguồn.'],['Sửa lỗi và audio','Văn bản nguồn là cơ sở kiểm chứng. Audio có thể thay thế dần khi chất lượng tốt hơn nhưng nguồn và phiên bản phải truy vết được.']]}
 },
 th:{
  about:{title:'เกี่ยวกับคลังพระธรรม',lead:'คลังดิจิทัลที่สงบและตรวจสอบแหล่งที่มาได้ สำหรับอ่าน ฟัง ศึกษา และอนุรักษ์พระไตรปิฎกบาลีเถรวาท',sections:[['สิ่งที่กำลังสร้าง','รวมบัญชีพระสูตร การอ่านฉบับเต็ม แหล่งอ้างอิง PDF ที่สร้างจากข้อความ เสียงอ่าน และการบันทึกความคืบหน้าไว้ในที่เดียว'],['แนวทางของเรา','เลือกฉบับที่ระบุที่มาและผู้แปลได้ชัดเจน AI ช่วยงานซอฟต์แวร์และตรวจคุณภาพได้ แต่ห้ามแต่งพระสูตร'],['ภาษา','ส่วนติดต่อผู้ใช้แปลเป็นภาษาที่เลือก ส่วนพระสูตรใช้เฉพาะคำแปลที่มีแหล่งที่มา หากต้องใช้ภาษาอังกฤษชั่วคราวจะระบุชัดเจน'],['การอนุรักษ์','ข้อมูลและเสียงอาจสำรองหลายผู้ให้บริการ โดยคงที่มา สิทธิ และข้อมูลเวอร์ชันไว้']]},
  privacy:{title:'นโยบายความเป็นส่วนตัว',lead:'สรุปว่าคลังเก็บข้อมูลใดและจะจัดการ analytics หรือโฆษณาอย่างไรหากเปิดใช้',sections:[['ข้อมูลในอุปกรณ์','ความคืบหน้าการอ่านและข้อความที่บันทึกอาจเก็บในเบราว์เซอร์ของคุณโดยไม่ต้องมีบัญชี'],['บันทึกเซิร์ฟเวอร์','ผู้ให้บริการโฮสติ้งอาจประมวลผลข้อมูลเทคนิคพื้นฐานเพื่อความปลอดภัยและความเสถียร'],['Analytics และโฆษณา','การอ่านพระสูตรไม่ต้องใช้คุกกี้โฆษณา หากเปิดใช้บริการเสริมจะมีการแจ้งและขอความยินยอมตามที่จำเป็น'],['บริการภายนอก','SuttaCentral, YouTube, คลังเก็บข้อมูล และ CDN มีนโยบายความเป็นส่วนตัวของตนเอง']]},
  terms:{title:'เงื่อนไขการใช้งาน',lead:'เงื่อนไขเรียบง่ายเพื่อให้คลังเปิดกว้าง มีประโยชน์ และโปร่งใส',sections:[['วัตถุประสงค์','ใช้เพื่ออ่าน ฟัง ศึกษา และอ้างอิง'],['สิทธิของข้อความ','พระสูตรและคำแปลอาจมีใบอนุญาตต่างกัน เรารักษาการระบุที่มาและลิงก์ต้นฉบับ'],['ความพร้อมใช้งาน','เนื้อหาและระบบอาจเปลี่ยนเมื่อมีการแก้ไขหรือปรับปรุงเสียง'],['การใช้อย่างรับผิดชอบ','ห้ามละเมิดระบบ ทำให้บริการล่ม หรือใช้ในทางที่ผิดกฎหมายหรือสิทธิของผู้อื่น']]},
  'editorial-policy':{title:'แหล่งที่มาและนโยบายบรรณาธิการ',lead:'หลักเกณฑ์การนำพระสูตรเข้าคลัง การรักษาที่มา และการแก้ไขข้อผิดพลาด',sections:[['แหล่งที่มาก่อน','ใช้ฉบับหรือคลังที่ระบุตัวตนได้และเก็บข้อมูลให้ผู้อ่านตรวจสอบย้อนหลังได้'],['ไม่แต่งพระสูตร','AI ช่วยซอฟต์แวร์ การค้นหา QA และเสียงอ่านได้ แต่ห้ามสร้างข้อความพระสูตรที่ขาดหาย'],['การใช้ภาษาอังกฤษชั่วคราว','เมื่อไม่มีคำแปลที่เชื่อถือได้ จะแสดงภาษาอังกฤษได้เฉพาะเมื่อมีป้ายแจ้งชัดเจน'],['การแก้ไขและเสียง','ข้อความต้นฉบับเป็นหลักในการตรวจสอบ เสียงอ่านเปลี่ยนเวอร์ชันได้เมื่อคุณภาพดีขึ้นโดยต้องติดตามที่มาได้']]}
 },
 my:{
  about:{title:'စာကြည့်တိုက်အကြောင်း',lead:'ထေရဝါဒ ပါဠိတိပိဋကကို ဖတ်ရှု၊ နားထောင်၊ လေ့လာနှင့် ထိန်းသိမ်းရန် ရင်းမြစ်အခြေပြု ဒစ်ဂျစ်တယ်စာကြည့်တိုက်',sections:[['ကျွန်ုပ်တို့ တည်ဆောက်နေသည့်အရာ','ကျမ်းစာစာရင်း၊ စာသားအပြည့်အစုံ၊ ရင်းမြစ်၊ PDF၊ အသံနှင့် ဖတ်ရှုမှုတိုးတက်ချက်ကို တစ်နေရာတည်း စုစည်းထားသည်။'],['ကျွန်ုပ်တို့၏ နည်းလမ်း','သတ်မှတ်နိုင်သော မူရင်းနှင့် ဘာသာပြန်သူကို ဦးစားပေးသည်။ AI ကို ဆော့ဖ်ဝဲနှင့် QA အတွက်သာ သုံးပြီး ကျမ်းစာမဖန်တီးပါ။'],['ဘာသာစကားများ','UI ကို ရွေးထားသောဘာသာစကားဖြင့် ပြသည်။ ကျမ်းစာသည် ရင်းမြစ်ရှိသော ဘာသာပြန်ကိုသာ သုံးပြီး အင်္ဂလိပ် fallback ဖြစ်လျှင် ရှင်းလင်းစွာ အမှတ်အသားပြုသည်။'],['ထိန်းသိမ်းမှု','ဒေတာနှင့် အသံကို နေရာစုံတွင် မိတ္တူထားနိုင်သော်လည်း ရင်းမြစ်၊ အခွင့်အရေးနှင့် ဗားရှင်းကို ထိန်းသိမ်းထားသည်။']]},
  privacy:{title:'ကိုယ်ရေးအချက်အလက် မူဝါဒ',lead:'စာကြည့်တိုက်က ဘာကို သိမ်းဆည်းနိုင်ပြီး analytics သို့မဟုတ် ကြော်ငြာကို မည်သို့ ကိုင်တွယ်မည်ကို ရှင်းပြထားသည်။',sections:[['စက်ပေါ်ရှိဒေတာ','ဖတ်ရှုမှုတိုးတက်ချက်နှင့် သိမ်းထားသောကျမ်းပိုဒ်များကို ဘရောက်ဇာတွင်သာ သိမ်းနိုင်ပြီး အကောင့်မလိုပါ။'],['ဆာဗာမှတ်တမ်း','Hosting ဝန်ဆောင်မှုက လုံခြုံရေးနှင့် ယုံကြည်စိတ်ချရမှုအတွက် အခြေခံနည်းပညာဒေတာကို ကိုင်တွယ်နိုင်သည်။'],['Analytics နှင့် ကြော်ငြာ','ကျမ်းစာဖတ်ရန် ကြော်ငြာ cookie မလိုပါ။ နောင်တွင် အသုံးပြုလျှင် လိုအပ်သည့် အသိပေးချက်နှင့် သဘောတူညီမှုကို ပေးမည်။'],['ပြင်ပဝန်ဆောင်မှု','SuttaCentral, YouTube, archive နှင့် CDN တို့တွင် ကိုယ်ပိုင် privacy policy ရှိသည်။']]},
  terms:{title:'အသုံးပြုမှု စည်းကမ်းများ',lead:'စာကြည့်တိုက်ကို ပွင့်လင်း၊ အသုံးဝင်နှင့် ရှင်းလင်းစေရန် ရိုးရှင်းသော စည်းကမ်းများ',sections:[['ရည်ရွယ်ချက်','ဖတ်ရှု၊ နားထောင်၊ လေ့လာနှင့် ကိုးကားရန် ဖြစ်သည်။'],['ကျမ်းစာအခွင့်အရေး','မူရင်းနှင့် ဘာသာပြန်များတွင် လိုင်စင်မတူနိုင်ပြီး ရင်းမြစ်နှင့် ဂုဏ်ပြုဖော်ပြချက်ကို ထိန်းသိမ်းသည်။'],['ရရှိနိုင်မှု','ပြင်ဆင်မှု၊ ရင်းမြစ်ပြောင်းလဲမှုနှင့် အသံအရည်အသွေးတိုးတက်မှုကြောင့် အကြောင်းအရာ ပြောင်းနိုင်သည်။'],['တာဝန်ရှိအသုံးပြုမှု','ဝန်ဆောင်မှုကို မလွဲသုံး၊ access control မကျော်၊ စနစ်မတင်မကျ လုပ်ခြင်းနှင့် ဥပဒေချိုးဖောက်ခြင်း မပြုရ။']]},
  'editorial-policy':{title:'ရင်းမြစ်နှင့် တည်းဖြတ်မူဝါဒ',lead:'ကျမ်းစာကို စာကြည့်တိုက်ထဲသို့ ထည့်သွင်းပုံ၊ ရင်းမြစ်ကို ထိန်းသိမ်းပုံနှင့် အမှားပြင်ပုံ',sections:[['ရင်းမြစ်ကို ဦးစားပေး','သတ်မှတ်နိုင်သော ထုတ်ဝေမှု သို့မဟုတ် ယုံကြည်ရသော repository မှသာ ကျမ်းစာကို ယူပြီး စစ်ဆေးနိုင်ရန် provenance ထိန်းသိမ်းသည်။'],['AI ဖြင့် မဖန်တီး','AI သည် ဆော့ဖ်ဝဲ၊ ရှာဖွေမှု၊ QA နှင့် အသံကို ကူညီနိုင်သော်လည်း ပျောက်နေသောကျမ်းစာကို မဖန်တီးရ။'],['ဘာသာစကား fallback','ရွေးထားသောဘာသာစကားတွင် ယုံကြည်ရသောစာသားမရှိလျှင် အင်္ဂလိပ်စာကို ရှင်းလင်းသော အသိပေးချက်ဖြင့်သာ ပြသည်။'],['အမှားပြင်နှင့် အသံ','စာသားမူရင်းသည် စစ်ဆေးရာ အခြေခံဖြစ်ပြီး အသံကို အရည်အသွေးတိုးတက်သလို ပြန်လည်ထုတ်နိုင်သည်။']]}
 },
 si:{
  about:{title:'පුස්තකාලය ගැන',lead:'ථෙරවාද පාලි ත්‍රිපිටකය කියවීමට, සවන් දීමට, අධ්‍යයනයට හා සංරක්ෂණයට මූලාශ්‍ර-සවිස්තර ඩිජිටල් පුස්තකාලයක්.',sections:[['අප ගොඩනඟන්නේ','නාමාවලිය, සම්පූර්ණ පාඨ, මූලාශ්‍ර, PDF, ශ්‍රව්‍ය සහ කියවීමේ ප්‍රගතිය එකම ස්ථානයක සපයයි.'],['අපගේ ක්‍රමය','හඳුනාගත හැකි සංස්කරණ සහ පරිවර්තකයන් ප්‍රමුඛ කරයි. AI මෘදුකාංග සහ QA සඳහා භාවිත කළ හැකි නමුත් ධර්ම පාඨ නිර්මාණය නොකරයි.'],['භාෂා','අතුරුමුහුණත තෝරාගත් භාෂාවෙන් ඇත. සූත්‍ර පාඨ සඳහා මූලාශ්‍ර සහිත පරිවර්තන පමණක් භාවිත වන අතර ඉංග්‍රීසි fallback පැහැදිලිව සලකුණු කරයි.'],['සංරක්ෂණය','දත්ත හා ශ්‍රව්‍ය පිටපත් ස්ථාන කිහිපයක තබාගත හැකි නමුත් මූලාශ්‍ර, හිමිකම් සහ අනුවාද තොරතුරු රඳවාගනී.']]},
  privacy:{title:'පෞද්ගලිකත්ව ප්‍රතිපත්තිය',lead:'පුස්තකාලය තබාගන්නා දත්ත සහ analytics හෝ දැන්වීම් පසුව භාවිත කළහොත් එය කළමනාකරණය කරන ආකාරය.',sections:[['උපාංගයේ දත්ත','කියවීමේ ප්‍රගතිය සහ සුරකින ලද කොටස් ඔබේ බ්‍රවුසරයේ තබාගත හැකි අතර ගිණුමක් අවශ්‍ය නොවේ.'],['සේවාදායක ලොග්','ආරක්ෂාව සහ විශ්වාසනීයතාව සඳහා hosting සේවාවන් මූලික තාක්ෂණික දත්ත සැකසිය හැක.'],['Analytics සහ දැන්වීම්','සූත්‍ර කියවීමට දැන්වීම් cookie අවශ්‍ය නොවේ. පසුව සක්‍රීය කළහොත් අවශ්‍ය දැනුම්දීම සහ අනුමැතිය ලබා දෙනු ඇත.'],['බාහිර සේවා','SuttaCentral, YouTube, archive සහ CDN සේවාවන්ට තමන්ගේ පෞද්ගලිකත්ව ප්‍රතිපත්ති ඇත.']]},
  terms:{title:'භාවිත කොන්දේසි',lead:'පුස්තකාලය විවෘත, ප්‍රයෝජනවත් සහ විනිවිද පවත්වාගැනීමට සරල කොන්දේසි.',sections:[['අරමුණ','කියවීම, සවන් දීම, අධ්‍යයනය සහ යොමු කිරීම සඳහා වේ.'],['පාඨ හිමිකම්','මූලාශ්‍ර සහ පරිවර්තනවල බලපත්‍ර වෙනස් විය හැකි අතර මූලාශ්‍ර සහ කර්තෘත්වය රඳවාගනී.'],['ලබාගත හැකියාව','නිවැරදි කිරීම්, මූලාශ්‍ර වෙනස්වීම් සහ ශ්‍රව්‍ය වැඩිදියුණු කිරීම් සමඟ සේවාව වෙනස් විය හැක.'],['වගකීම් සහිත භාවිතය','සේවාව අපයෝජනය කිරීම, පාලන මඟහැරීම, පද්ධතිය අධික බර කිරීම හෝ නීති උල්ලංඝනය කිරීම තහනම්ය.']]},
  'editorial-policy':{title:'මූලාශ්‍ර සහ සංස්කරණ ප්‍රතිපත්තිය',lead:'ධර්ම පාඨ පුස්තකාලයට ඇතුළත් කරන ආකාරය, provenance රඳවන ආකාරය සහ නිවැරදි කිරීම්.',sections:[['මූලාශ්‍ර ප්‍රමුඛයි','හඳුනාගත හැකි සංස්කරණ හෝ විශ්වාසනීය repositories භාවිත කර ස්වාධීන සත්‍යාපනය සඳහා තොරතුරු රඳවාගනී.'],['AI විසින් ධර්ම පාඨ නොසෑදේ','AI මෘදුකාංග, සෙවුම්, QA සහ ශ්‍රව්‍යයට උදව් කළ හැකි නමුත් අහිමි පාඨ නිර්මාණය නොකරයි.'],['භාෂා fallback','විශ්වාසනීය දේශීය පරිවර්තනයක් නොමැති විට ඉංග්‍රීසි පාඨය පැහැදිලි දැනුම්දීමක් සමඟ පමණක් පෙන්වයි.'],['නිවැරදි කිරීම සහ ශ්‍රව්‍ය','සත්‍යාපනය සඳහා පාඨය ප්‍රධාන වන අතර ශ්‍රව්‍ය ගුණාත්මකභාවය වැඩිදියුණු වූ විට අනුවාදගත කළ හැක.']]}
 },
 km:{
  about:{title:'អំពីបណ្ណាល័យ',lead:'បណ្ណាល័យឌីជីថលផ្អែកលើប្រភព សម្រាប់អាន ស្តាប់ សិក្សា និងអភិរក្សព្រះត្រៃបិដកបាលីថេរវាទ។',sections:[['អ្វីដែលយើងកំពុងសាងសង់','រួមបញ្ចូលបញ្ជីគម្ពីរ អត្ថបទពេញ ប្រភព PDF សំឡេង និងការរក្សាវឌ្ឍនភាពអាននៅកន្លែងតែមួយ។'],['វិធីសាស្ត្រ','ប្រើសំណៅអាចកំណត់អត្តសញ្ញាណ និងបញ្ជាក់អ្នកបកប្រែ។ AI អាចជួយផ្នែកកម្មវិធីនិង QA ប៉ុន្តែមិនអាចបង្កើតគម្ពីរបានទេ។'],['ភាសា','UI បង្ហាញជាភាសាដែលបានជ្រើស។ អត្ថបទគម្ពីរប្រើតែការបកប្រែមានប្រភព ហើយ fallback អង់គ្លេសត្រូវបញ្ជាក់ច្បាស់។'],['ការអភិរក្ស','ទិន្នន័យនិងសំឡេងអាចបម្រុងទុកច្រើនទីតាំង ដោយរក្សាប្រភព សិទ្ធិ និងកំណែ។']]},
  privacy:{title:'គោលការណ៍ឯកជនភាព',lead:'សេចក្ដីសង្ខេបអំពីទិន្នន័យដែលបណ្ណាល័យអាចរក្សា និងរបៀបគ្រប់គ្រង analytics ឬការផ្សាយពាណិជ្ជកម្ម។',sections:[['ទិន្នន័យលើឧបករណ៍','វឌ្ឍនភាពអាន និងកថាខណ្ឌដែលបានរក្សាអាចនៅក្នុង browser របស់អ្នក ដោយមិនចាំបាច់មានគណនី។'],['កំណត់ត្រាម៉ាស៊ីនមេ','អ្នកផ្តល់ hosting អាចដំណើរការទិន្នន័យបច្ចេកទេសមូលដ្ឋានសម្រាប់សុវត្ថិភាពនិងភាពជឿជាក់។'],['Analytics និងការផ្សាយពាណិជ្ជកម្ម','ការអានគម្ពីរមិនត្រូវការ cookie ផ្សាយពាណិជ្ជកម្មទេ។ ប្រសិនបើបើកនៅពេលក្រោយ នឹងមានសេចក្ដីជូនដំណឹង និងការយល់ព្រមតាមតម្រូវការ។'],['សេវាក្រៅ','SuttaCentral, YouTube, archive និង CDN មានគោលការណ៍ឯកជនភាពរបស់ខ្លួន។']]},
  terms:{title:'លក្ខខណ្ឌប្រើប្រាស់',lead:'លក្ខខណ្ឌសាមញ្ញសម្រាប់រក្សាបណ្ណាល័យឱ្យបើកចំហ មានប្រយោជន៍ និងតម្លាភាព។',sections:[['គោលបំណង','សម្រាប់អាន ស្តាប់ សិក្សា និងយោង។'],['សិទ្ធិអត្ថបទ','ប្រភពនិងការបកប្រែអាចមានអាជ្ញាបណ្ណខុសគ្នា ហើយការបញ្ជាក់ប្រភពត្រូវបានរក្សា។'],['ភាពអាចប្រើបាន','ខ្លឹមសារនិងប្រព័ន្ធអាចផ្លាស់ប្តូរតាមការកែសម្រួល និងការកែលម្អសំឡេង។'],['ការប្រើប្រាស់ដោយទទួលខុសត្រូវ','កុំរំលោភសេវា រំលងការគ្រប់គ្រង ចំណាយធនធានលើសកម្រិត ឬរំលោភច្បាប់និងសិទ្ធិអ្នកដទៃ។']]},
  'editorial-policy':{title:'ប្រភព និងគោលការណ៍កែសម្រួល',lead:'របៀបយកគម្ពីរចូលបណ្ណាល័យ រក្សាប្រភព និងកែសម្រួលកំហុស។',sections:[['ប្រភពជាមុន','ប្រើសំណៅឬ repository ដែលអាចកំណត់បាន និងរក្សា provenance សម្រាប់ផ្ទៀងផ្ទាត់។'],['មិនបង្កើតគម្ពីរដោយ AI','AI អាចជួយកម្មវិធី ស្វែងរក QA និងសំឡេង ប៉ុន្តែមិនអាចបង្កើតអត្ថបទគម្ពីរដែលខ្វះ។'],['Fallback ភាសា','បើគ្មានការបកប្រែដែលទុកចិត្តបាន អង់គ្លេសអាចបង្ហាញតែជាមួយសេចក្ដីជូនដំណឹងច្បាស់។'],['ការកែសម្រួលនិងសំឡេង','អត្ថបទប្រភពជាគោលសម្រាប់ផ្ទៀងផ្ទាត់ ហើយសំឡេងអាចធ្វើកំណែថ្មីពេលគុណភាពប្រសើរ។']]}
 },
 lo:{
  about:{title:'ກ່ຽວກັບຫໍສະໝຸດ',lead:'ຫໍສະໝຸດດິຈິຕອນທີ່ອີງແຫຼ່ງ ສຳລັບອ່ານ ຟັງ ສຶກສາ ແລະອະນຸລັກພຣະໄຕປິດົກບາລີເຖຣະວາດ.',sections:[['ສິ່ງທີ່ກຳລັງສ້າງ','ລວມລາຍການພຣະສູດ ເນື້ອຫາເຕັມ ແຫຼ່ງອ້າງອີງ PDF ສຽງ ແລະຄວາມຄືບໜ້າການອ່ານ.'],['ແນວທາງ','ໃຫ້ຄວາມສຳຄັນແກ່ສະບັບທີ່ລະບຸແຫຼ່ງແລະຜູ້ແປໄດ້. AI ຊ່ວຍຊອບແວແລະ QA ແຕ່ບໍ່ສ້າງພຣະສູດ.'],['ພາສາ','UI ໃຊ້ພາສາທີ່ເລືອກ. ຂໍ້ຄວາມພຣະສູດໃຊ້ສະເພາະຄຳແປທີ່ມີແຫຼ່ງ ແລະ fallback ອັງກິດຈະຖືກລະບຸຊັດ.'],['ການອະນຸລັກ','ຂໍ້ມູນແລະສຽງອາດສຳຮອງຫຼາຍບ່ອນ ໂດຍຮັກສາແຫຼ່ງ ສິດ ແລະສະບັບ.']]},
  privacy:{title:'ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ',lead:'ສະຫຼຸບຂໍ້ມູນທີ່ຫໍສະໝຸດອາດຈັດເກັບ ແລະວິທີຈັດການ analytics ຫຼືໂຄສະນາ.',sections:[['ຂໍ້ມູນໃນອຸປະກອນ','ຄວາມຄືບໜ້າການອ່ານແລະຂໍ້ຄວາມທີ່ບັນທຶກອາດຢູ່ໃນ browser ໂດຍບໍ່ຕ້ອງມີບັນຊີ.'],['ບັນທຶກ server','ຜູ້ໃຫ້ບໍລິການ hosting ອາດປະມວນຂໍ້ມູນເຕັກນິກພື້ນຖານເພື່ອຄວາມປອດໄພ.'],['Analytics ແລະໂຄສະນາ','ການອ່ານພຣະສູດບໍ່ຕ້ອງໃຊ້ cookie ໂຄສະນາ. ຖ້າເປີດໃຊ້ພາຍຫຼັງຈະມີການແຈ້ງແລະຂໍຄວາມຍິນຍອມຕາມຈຳເປັນ.'],['ບໍລິການພາຍນອກ','SuttaCentral, YouTube, archive ແລະ CDN ມີນະໂຍບາຍຂອງຕົນເອງ.']]},
  terms:{title:'ເງື່ອນໄຂການໃຊ້',lead:'ເງື່ອນໄຂງ່າຍໆ ເພື່ອໃຫ້ຫໍສະໝຸດເປີດ ມີປະໂຫຍດ ແລະໂປ່ງໃສ.',sections:[['ຈຸດປະສົງ','ສຳລັບອ່ານ ຟັງ ສຶກສາ ແລະອ້າງອີງ.'],['ສິດເນື້ອຫາ','ແຫຼ່ງແລະຄຳແປອາດມີໃບອະນຸຍາດຕ່າງກັນ ແລະຈະຮັກສາການອ້າງອີງ.'],['ຄວາມພ້ອມ','ເນື້ອຫາແລະລະບົບອາດປ່ຽນຕາມການແກ້ໄຂແລະພັດທະນາສຽງ.'],['ການໃຊ້ຢ່າງຮັບຜິດຊອບ','ຫ້າມລະເມີດບໍລິການ ຂ້າມ access control ເຮັດໃຫ້ລະບົບໂຫຼດເກີນ ຫຼືລະເມີດກົດໝາຍ.']]},
  'editorial-policy':{title:'ແຫຼ່ງທີ່ມາ ແລະນະໂຍບາຍບັນນາທິການ',lead:'ວິທີນຳພຣະສູດເຂົ້າຫໍສະໝຸດ ຮັກສາ provenance ແລະແກ້ໄຂຂໍ້ຜິດພາດ.',sections:[['ແຫຼ່ງກ່ອນ','ໃຊ້ສະບັບຫຼື repository ທີ່ລະບຸໄດ້ ແລະຮັກສາຂໍ້ມູນໃຫ້ກວດສອບໄດ້.'],['ບໍ່ສ້າງພຣະສູດດ້ວຍ AI','AI ຊ່ວຍຊອບແວ ຄົ້ນຫາ QA ແລະສຽງ ແຕ່ບໍ່ສາມາດສ້າງຂໍ້ຄວາມພຣະສູດທີ່ຂາດ.'],['Fallback ພາສາ','ຖ້າບໍ່ມີຄຳແປທີ່ເຊື່ອຖື ອັງກິດຈະສະແດງສະເພາະພ້ອມຄຳແຈ້ງຊັດເຈນ.'],['ການແກ້ໄຂແລະສຽງ','ຂໍ້ຄວາມຕົ້ນສະບັບເປັນຫຼັກກວດສອບ ແລະສຽງສາມາດອອກສະບັບໃໝ່ເມື່ອຄຸນນະພາບດີຂຶ້ນ.']]}
 },
 zh:{
  about:{title:'关于本馆',lead:'一个注重来源、适合阅读、聆听、研究与保存上座部巴利三藏的数字图书馆。',sections:[['我们在建设什么','把规范目录、全文阅读、可核查来源、自动生成 PDF、音频和阅读进度集中到一个适合手机、平板和电脑的图书馆。'],['我们的原则','优先采用可识别的版本并标明译者或上游来源。AI 可帮助软件、无障碍和质检，但不得编造经文。'],['语言','公共界面使用所选语言。经文只采用有来源的译本；若暂时使用英文，会明确标注为 fallback。'],['长期保存','经文数据和音频可以镜像到多个存储服务，但必须保留来源、权利和版本信息。']]},
  privacy:{title:'隐私政策',lead:'用简明语言说明本馆可能保存哪些数据，以及未来若启用分析或广告时如何处理。',sections:[['设备上的数据','阅读进度和保存的经文摘录可以存放在您自己的浏览器中，无需账户。'],['服务器日志','托管服务可能为内容分发、安全和稳定性处理基础技术请求信息。'],['分析与广告','阅读经文不需要广告 Cookie。若以后启用分析或广告，将在需要时提供告知和同意控制。'],['第三方服务','SuttaCentral、YouTube、档案服务和 CDN 适用各自的隐私政策。']]},
  terms:{title:'使用条款',lead:'保持图书馆开放、实用和透明的简明条款。',sections:[['用途','本馆用于阅读、聆听、学习和参考。'],['经文与译本权利','不同来源和译本可能适用不同许可；本馆尽量保留署名和来源链接。'],['可用性','随着勘误、来源变化和音频升级，内容或基础设施可能调整。'],['负责任使用','不得滥用服务、绕过访问控制、恶意消耗资源或侵犯法律和他人权利。']]},
  'editorial-policy':{title:'来源与编辑原则',lead:'说明经文如何进入本馆、如何保存出处以及如何处理勘误。',sections:[['来源优先','经文来自可识别版本或可信数字库，并保留足够 provenance 以供独立核查。'],['绝不用 AI 编造经文','AI 可以辅助软件、搜索、质检和音频流程，但不得补写缺失经文或把生成文字冒充经典。'],['语言 fallback','所选语言没有可靠全文时，只能在清楚提示和保留译者来源的前提下暂时显示英文。'],['勘误与音频','文本来源是核查依据；音频可随着发音和质量改善而更新，但版本与来源必须可追溯。']]}
 }
};

export function infoCopy(kind:Kind,locale:Locale):InfoContent{
 const l=(locale in pages?locale:'en') as L;const p=pages[l][kind];const c=common[l];return {...p,transparency:c.transparency,transparencyBody:c.body,back:c.back};
}
