// Generated by scripts/generate_content_registry.py; do not edit by hand.
import corpus0 from '@/data/content/dn.vi.json';
import corpus1 from '@/data/content/sn/01.vi.json';
import corpus2 from '@/data/content/sn/02.vi.json';
import corpus3 from '@/data/content/sn/03.vi.json';

export const materializedVi:Record<string,unknown>=Object.assign({}, corpus0, corpus1, corpus2, corpus3);
