// Generated by scripts/generate_content_registry.py; do not edit by hand.
import corpus0 from '@/data/content/dn.vi.json';
import corpus1 from '@/data/content/an/01.vi.json';
import corpus2 from '@/data/content/an/02.vi.json';
import corpus3 from '@/data/content/an/03.vi.json';
import corpus4 from '@/data/content/an/04.vi.json';
import corpus5 from '@/data/content/an/05.vi.json';
import corpus6 from '@/data/content/an/06.vi.json';
import corpus7 from '@/data/content/an/07.vi.json';
import corpus8 from '@/data/content/an/08.vi.json';
import corpus9 from '@/data/content/an/09.vi.json';
import corpus10 from '@/data/content/an/10.vi.json';
import corpus11 from '@/data/content/an/11.vi.json';
import corpus12 from '@/data/content/sn/01.vi.json';
import corpus13 from '@/data/content/sn/02.vi.json';
import corpus14 from '@/data/content/sn/03.vi.json';
import corpus15 from '@/data/content/sn/04.vi.json';
import corpus16 from '@/data/content/sn/05.vi.json';
import corpus17 from '@/data/content/sn/06.vi.json';
import corpus18 from '@/data/content/sn/07.vi.json';
import corpus19 from '@/data/content/sn/08.vi.json';
import corpus20 from '@/data/content/sn/09.vi.json';
import corpus21 from '@/data/content/sn/10.vi.json';
import corpus22 from '@/data/content/sn/11.vi.json';
import corpus23 from '@/data/content/sn/12.vi.json';
import corpus24 from '@/data/content/sn/13.vi.json';
import corpus25 from '@/data/content/sn/14.vi.json';

export const materializedVi:Record<string,unknown>=Object.assign({}, corpus0, corpus1, corpus2, corpus3, corpus4, corpus5, corpus6, corpus7, corpus8, corpus9, corpus10, corpus11, corpus12, corpus13, corpus14, corpus15, corpus16, corpus17, corpus18, corpus19, corpus20, corpus21, corpus22, corpus23, corpus24, corpus25);
