import type {Locale} from '@/lib/i18n';

type PublicLocale='vi'|'th'|'my'|'si'|'km'|'lo'|'en'|'zh';

type Copy={
  brand:string; brandSub:string; primaryNav:string; mobileNav:string;
  home:string; collections:string; canon:string; library:string; listen:string; progress:string; search:string;
  footerDescription:string; libraryInfo:string; about:string; editorial:string; privacy:string; terms:string;
  readVerify:string; browse:string; dataProgress:string; reportCorrection:string; integrity:string;
  backLibrary:string; mp3Available:string; listenDownload:string; listenLabel:string; listenSub:string; openDownloadMp3:string; textSource:string;
  pdfGenerate:string; pdfGenerated:string; fullText:string; readHere:string; translation:string; source:string; verifySource:string;
  unavailable:string; fallbackTitle:string; fallbackBody:string; moreCollection:string; minutes:string;
  passageCollection:string; savedCount:string; copy:string; save:string;
};

const copies:Record<PublicLocale,Copy>={
  en:{brand:'Five Nikāya Collections',brandSub:'Early Buddhist scripture library',primaryNav:'Primary navigation',mobileNav:'Mobile navigation',home:'Home',collections:'Five Nikāyas',canon:'Pāli Canon',library:'Library',listen:'Listen',progress:'Library progress',search:'Search',footerDescription:'A reading, listening and preservation library for the Nikāyas, Vinaya and Abhidhamma with traceable source references.',libraryInfo:'Library',about:'About',editorial:'Sources & editorial policy',privacy:'Privacy',terms:'Terms',readVerify:'Read & verify',browse:'Browse the library',dataProgress:'Data progress',reportCorrection:'Report a correction',integrity:'Scripture text prioritizes verifiable sources; AI is not used to invent scripture.',backLibrary:'Library',mp3Available:'MP3 available',listenDownload:'Listen and download',listenLabel:'Listen',listenSub:'Prebuilt MP3 · all devices',openDownloadMp3:'Open / download MP3',textSource:'Text source',pdfGenerate:'Generate a PDF from this text',pdfGenerated:'Generated',fullText:'FULL TEXT',readHere:'Read here in the library',translation:'Translation',source:'SOURCE',verifySource:'Verify source',unavailable:'The requested translation is unavailable or temporarily could not be loaded.',fallbackTitle:'English text shown temporarily',fallbackBody:'A source-backed translation for the selected language is not available yet. The English translation is displayed clearly as a temporary fallback; the source and translator remain identified below.',moreCollection:'More in this collection',minutes:'min read',passageCollection:'Passage collection',savedCount:'saved',copy:'Copy',save:'Save'},
  vi:{brand:'Thư Viện Tam Tạng Pāli',brandSub:'Kinh · Luật · Vi Diệu Pháp Theravāda',primaryNav:'Điều hướng chính',mobileNav:'Điều hướng di động',home:'Trang chủ',collections:'5 bộ Nikāya',canon:'Tam Tạng Pāli',library:'Tìm kinh',listen:'Nghe kinh',progress:'Tiến độ thư viện',search:'Tìm',footerDescription:'Thư viện đọc, nghe và lưu giữ kinh điển Nikāya, Luật tạng và Vi Diệu Pháp với nguồn đối chiếu rõ ràng.',libraryInfo:'Thư viện',about:'Giới thiệu',editorial:'Nguồn & nguyên tắc biên tập',privacy:'Quyền riêng tư',terms:'Điều khoản sử dụng',readVerify:'Đọc & kiểm chứng',browse:'Tra cứu kinh',dataProgress:'Tiến độ dữ liệu',reportCorrection:'Báo lỗi / góp ý nguồn',integrity:'Kinh văn ưu tiên nguồn có thể kiểm tra; AI không được dùng để bịa kinh văn.',backLibrary:'Thư viện',mp3Available:'Có MP3',listenDownload:'Nghe và tải',listenLabel:'Nghe',listenSub:'MP3 dựng sẵn · mọi thiết bị',openDownloadMp3:'Mở / tải MP3',textSource:'Nguồn văn bản',pdfGenerate:'Tạo PDF từ chính nội dung bài kinh đang đọc',pdfGenerated:'Tự tạo',fullText:'TOÀN VĂN BÀI KINH',readHere:'Đọc ngay tại thư viện',translation:'Bản dịch',source:'NGUỒN',verifySource:'Đối chiếu nguồn',unavailable:'Bản toàn văn của ngôn ngữ này hiện chưa có hoặc tạm thời không tải được.',fallbackTitle:'Tạm hiển thị bản tiếng Anh',fallbackBody:'Chưa có bản dịch có nguồn đáng tin cậy cho ngôn ngữ đang chọn. Thư viện tạm hiển thị bản tiếng Anh và vẫn ghi rõ nguồn cùng người dịch.',moreCollection:'Đọc tiếp trong cùng tạng',minutes:'phút đọc',passageCollection:'Sưu tầm đoạn kinh',savedCount:'đã lưu',copy:'Sao chép',save:'Lưu'},
  th:{brand:'คลังพระไตรปิฎกบาลี',brandSub:'พระสูตร · พระวินัย · พระอภิธรรมเถรวาท',primaryNav:'เมนูหลัก',mobileNav:'เมนูมือถือ',home:'หน้าแรก',collections:'นิกาย 5 หมวด',canon:'พระไตรปิฎกบาลี',library:'ค้นพระสูตร',listen:'ฟัง',progress:'ความคืบหน้าคลัง',search:'ค้นหา',footerDescription:'คลังสำหรับอ่าน ฟัง และอนุรักษ์พระสูตรนิกาย พระวินัย และพระอภิธรรม พร้อมแหล่งอ้างอิงที่ตรวจสอบได้',libraryInfo:'คลังพระธรรม',about:'เกี่ยวกับ',editorial:'แหล่งที่มาและนโยบายบรรณาธิการ',privacy:'ความเป็นส่วนตัว',terms:'เงื่อนไขการใช้งาน',readVerify:'อ่านและตรวจสอบ',browse:'ค้นในคลัง',dataProgress:'ความคืบหน้าข้อมูล',reportCorrection:'แจ้งข้อแก้ไข',integrity:'ข้อความพระสูตรให้ความสำคัญกับแหล่งที่ตรวจสอบได้ และไม่ใช้ AI แต่งพระสูตรขึ้นเอง',backLibrary:'คลังพระสูตร',mp3Available:'มี MP3',listenDownload:'ฟังและดาวน์โหลด',listenLabel:'ฟัง',listenSub:'MP3 ที่จัดทำไว้แล้ว · ใช้ได้ทุกอุปกรณ์',openDownloadMp3:'เปิด / ดาวน์โหลด MP3',textSource:'แหล่งข้อความ',pdfGenerate:'สร้าง PDF จากข้อความนี้',pdfGenerated:'สร้างอัตโนมัติ',fullText:'ข้อความฉบับเต็ม',readHere:'อ่านฉบับเต็มในคลัง',translation:'คำแปล',source:'แหล่งที่มา',verifySource:'ตรวจสอบแหล่งที่มา',unavailable:'ยังไม่มีคำแปลภาษาที่เลือก หรือแหล่งข้อมูลไม่พร้อมใช้งานชั่วคราว',fallbackTitle:'แสดงข้อความภาษาอังกฤษชั่วคราว',fallbackBody:'ยังไม่มีคำแปลที่มีแหล่งอ้างอิงน่าเชื่อถือสำหรับภาษาที่เลือก จึงแสดงคำแปลภาษาอังกฤษชั่วคราวพร้อมระบุแหล่งที่มาและผู้แปลอย่างชัดเจน',moreCollection:'อ่านต่อในหมวดเดียวกัน',minutes:'นาที',passageCollection:'เก็บข้อความที่เลือก',savedCount:'บันทึกแล้ว',copy:'คัดลอก',save:'บันทึก'},
  my:{brand:'ပါဠိ တိပိဋက စာကြည့်တိုက်',brandSub:'သုတ္တန် · ဝိနယ · အဘိဓမ္မာ ထေရဝါဒ',primaryNav:'အဓိက လမ်းညွှန်',mobileNav:'မိုဘိုင်း လမ်းညွှန်',home:'ပင်မ',collections:'နိကာယ် ၅ ရပ်',canon:'ပါဠိ တိပိဋက',library:'သုတ်ရှာရန်',listen:'နားထောင်ရန်',progress:'စာကြည့်တိုက် တိုးတက်မှု',search:'ရှာဖွေ',footerDescription:'နိကာယ်သုတ်တော်များ၊ ဝိနယနှင့် အဘိဓမ္မာကို ဖတ်ရှု၊ နားထောင်၊ ထိန်းသိမ်းရန်နှင့် စစ်ဆေးနိုင်သော မူရင်းရင်းမြစ်များပါသော စာကြည့်တိုက်',libraryInfo:'စာကြည့်တိုက်',about:'အကြောင်း',editorial:'ရင်းမြစ်နှင့် တည်းဖြတ်မူဝါဒ',privacy:'ကိုယ်ရေးအချက်အလက်',terms:'အသုံးပြုမှု စည်းကမ်းများ',readVerify:'ဖတ်ရှု၍ စစ်ဆေးရန်',browse:'စာကြည့်တိုက် ရှာဖွေရန်',dataProgress:'ဒေတာ တိုးတက်မှု',reportCorrection:'အမှားပြင်ရန် တင်ပြပါ',integrity:'ကျမ်းစာသည် စစ်ဆေးနိုင်သော ရင်းမြစ်ကို ဦးစားပေးပြီး AI ဖြင့် ကျမ်းစာအသစ် မဖန်တီးပါ',backLibrary:'စာကြည့်တိုက်',mp3Available:'MP3 ရှိသည်',listenDownload:'နားထောင် / ဒေါင်းလုဒ်',listenLabel:'နားထောင်',listenSub:'ကြိုတင်ဖန်တီးထားသော MP3 · စက်အားလုံး',openDownloadMp3:'MP3 ဖွင့် / ဒေါင်းလုဒ်',textSource:'စာသားရင်းမြစ်',pdfGenerate:'ဤစာသားမှ PDF ဖန်တီးရန်',pdfGenerated:'ဖန်တီးထားသည်',fullText:'စာသားအပြည့်အစုံ',readHere:'စာကြည့်တိုက်တွင် အပြည့်အစုံဖတ်ရန်',translation:'ဘာသာပြန်',source:'ရင်းမြစ်',verifySource:'ရင်းမြစ် စစ်ဆေးရန်',unavailable:'ရွေးထားသော ဘာသာစကားအတွက် ဘာသာပြန်မရှိသေးပါ သို့မဟုတ် ယာယီမရနိုင်ပါ',fallbackTitle:'အင်္ဂလိပ်စာကို ယာယီပြထားသည်',fallbackBody:'ရွေးထားသော ဘာသာစကားအတွက် ယုံကြည်ရသော ရင်းမြစ်ပါ ဘာသာပြန်မရှိသေးသဖြင့် အင်္ဂလိပ်ဘာသာပြန်ကို ယာယီပြထားပြီး ရင်းမြစ်နှင့် ဘာသာပြန်သူကို ရှင်းလင်းစွာ ဖော်ပြထားသည်',moreCollection:'ဤနိကာယ်တွင် ဆက်ဖတ်ရန်',minutes:'မိနစ်',passageCollection:'ကျမ်းပိုဒ် စုစည်းမှု',savedCount:'သိမ်းထားပြီး',copy:'ကူးယူ',save:'သိမ်းရန်'},
  si:{brand:'පාලි ත්‍රිපිටක පුස්තකාලය',brandSub:'සුත්ත · විනය · අභිධම්ම ථෙරවාද',primaryNav:'ප්‍රධාන සංචාලනය',mobileNav:'ජංගම සංචාලනය',home:'මුල් පිටුව',collections:'නිකාය 5',canon:'පාලි ත්‍රිපිටකය',library:'සුත්ත සොයන්න',listen:'සවන් දෙන්න',progress:'පුස්තකාල ප්‍රගතිය',search:'සොයන්න',footerDescription:'නිකාය, විනය සහ අභිධම්ම කියවීමට, සවන් දීමට සහ සංරක්ෂණයට සත්‍යාපනය කළ හැකි මූලාශ්‍ර සහිත පුස්තකාලයක්.',libraryInfo:'පුස්තකාලය',about:'අප ගැන',editorial:'මූලාශ්‍ර සහ සංස්කරණ ප්‍රතිපත්තිය',privacy:'පෞද්ගලිකත්වය',terms:'භාවිත කොන්දේසි',readVerify:'කියවන්න සහ සත්‍යාපනය කරන්න',browse:'පුස්තකාලය සොයන්න',dataProgress:'දත්ත ප්‍රගතිය',reportCorrection:'නිවැරදි කිරීමක් දන්වන්න',integrity:'ධර්ම පාඨ සඳහා සත්‍යාපනය කළ හැකි මූලාශ්‍ර ප්‍රමුඛ වේ; AI මඟින් සූත්‍ර නිර්මාණය නොකෙරේ.',backLibrary:'පුස්තකාලය',mp3Available:'MP3 ඇත',listenDownload:'සවන් දෙන්න සහ බාගන්න',listenLabel:'සවන් දෙන්න',listenSub:'පෙර සකස් කළ MP3 · සියලු උපාංග',openDownloadMp3:'MP3 විවෘත / බාගන්න',textSource:'පාඨ මූලාශ්‍රය',pdfGenerate:'මෙම පාඨයෙන් PDF සාදන්න',pdfGenerated:'සාදන ලදි',fullText:'සම්පූර්ණ පාඨය',readHere:'පුස්තකාලයේ සම්පූර්ණයෙන් කියවන්න',translation:'පරිවර්තනය',source:'මූලාශ්‍රය',verifySource:'මූලාශ්‍රය සත්‍යාපනය කරන්න',unavailable:'තෝරාගත් භාෂාවේ විශ්වාසදායක පරිවර්තනය තවම නොමැති හෝ තාවකාලිකව ලබාගත නොහැක.',fallbackTitle:'ඉංග්‍රීසි පාඨය තාවකාලිකව පෙන්වයි',fallbackBody:'තෝරාගත් භාෂාව සඳහා මූලාශ්‍ර සහිත විශ්වාසදායක පරිවර්තනයක් තවම නොමැති බැවින් ඉංග්‍රීසි පරිවර්තනය තාවකාලිකව පෙන්වා මූලාශ්‍රය සහ පරිවර්තකයා පැහැදිලිව දක්වයි.',moreCollection:'මෙම නිකායේ තවත්',minutes:'මිනිත්තු',passageCollection:'පාඨ කොටස් එකතුව',savedCount:'සුරකින ලදි',copy:'පිටපත් කරන්න',save:'සුරකින්න'},
  km:{brand:'បណ្ណាល័យព្រះត្រៃបិដកបាលី',brandSub:'សុត្តន្ត · វិន័យ · អភិធម្ម ថេរវាទ',primaryNav:'ម៉ឺនុយមេ',mobileNav:'ម៉ឺនុយទូរស័ព្ទ',home:'ទំព័រដើម',collections:'និកាយ ៥',canon:'ព្រះត្រៃបិដកបាលី',library:'ស្វែងរកសូត្រ',listen:'ស្តាប់',progress:'វឌ្ឍនភាពបណ្ណាល័យ',search:'ស្វែងរក',footerDescription:'បណ្ណាល័យសម្រាប់អាន ស្តាប់ និងអភិរក្សនិកាយ វិន័យ និងអភិធម្ម ដោយមានប្រភពអាចផ្ទៀងផ្ទាត់បាន។',libraryInfo:'បណ្ណាល័យ',about:'អំពីយើង',editorial:'ប្រភព និងគោលការណ៍កែសម្រួល',privacy:'ឯកជនភាព',terms:'លក្ខខណ្ឌប្រើប្រាស់',readVerify:'អាន និងផ្ទៀងផ្ទាត់',browse:'ស្វែងរកក្នុងបណ្ណាល័យ',dataProgress:'វឌ្ឍនភាពទិន្នន័យ',reportCorrection:'រាយការណ៍កំហុស',integrity:'អត្ថបទព្រះធម៌ផ្តល់អាទិភាពដល់ប្រភពអាចផ្ទៀងផ្ទាត់បាន ហើយមិនប្រើ AI បង្កើតព្រះសូត្រឡើងថ្មីទេ។',backLibrary:'បណ្ណាល័យ',mp3Available:'មាន MP3',listenDownload:'ស្តាប់ និងទាញយក',listenLabel:'ស្តាប់',listenSub:'MP3 រៀបចំរួច · គ្រប់ឧបករណ៍',openDownloadMp3:'បើក / ទាញយក MP3',textSource:'ប្រភពអត្ថបទ',pdfGenerate:'បង្កើត PDF ពីអត្ថបទនេះ',pdfGenerated:'បានបង្កើត',fullText:'អត្ថបទពេញ',readHere:'អានពេញនៅក្នុងបណ្ណាល័យ',translation:'ការបកប្រែ',source:'ប្រភព',verifySource:'ផ្ទៀងផ្ទាត់ប្រភព',unavailable:'មិនទាន់មានការបកប្រែដែលអាចទុកចិត្តបានសម្រាប់ភាសានេះ ឬប្រភពមិនអាចប្រើបានបណ្តោះអាសន្ន។',fallbackTitle:'បង្ហាញអត្ថបទអង់គ្លេសបណ្តោះអាសន្ន',fallbackBody:'មិនទាន់មានការបកប្រែមានប្រភពដែលអាចទុកចិត្តបានសម្រាប់ភាសាដែលបានជ្រើស ដូច្នេះបង្ហាញការបកប្រែអង់គ្លេសបណ្តោះអាសន្ន និងបញ្ជាក់ប្រភពនិងអ្នកបកប្រែឱ្យច្បាស់។',moreCollection:'អានបន្តក្នុងនិកាយនេះ',minutes:'នាទី',passageCollection:'បណ្ដុំកថាខណ្ឌ',savedCount:'បានរក្សាទុក',copy:'ចម្លង',save:'រក្សាទុក'},
  lo:{brand:'ຫໍພຣະໄຕປິດົກບາລີ',brandSub:'ສຸດຕັນຕະ · ວິໄນ · ອະພິທຳ ເຖຣະວາດ',primaryNav:'ເມນູຫຼັກ',mobileNav:'ເມນູມືຖື',home:'ໜ້າຫຼັກ',collections:'ນິກາຍ 5',canon:'ພຣະໄຕປິດົກບາລີ',library:'ຄົ້ນພຣະສູດ',listen:'ຟັງ',progress:'ຄວາມຄືບໜ້າຫໍສະໝຸດ',search:'ຄົ້ນຫາ',footerDescription:'ຫໍສະໝຸດສຳລັບອ່ານ ຟັງ ແລະອະນຸລັກນິກາຍ ວິໄນ ແລະອະພິທຳ ພ້ອມແຫຼ່ງອ້າງອີງທີ່ກວດສອບໄດ້.',libraryInfo:'ຫໍສະໝຸດ',about:'ກ່ຽວກັບ',editorial:'ແຫຼ່ງທີ່ມາ ແລະນະໂຍບາຍບັນນາທິການ',privacy:'ຄວາມເປັນສ່ວນຕົວ',terms:'ເງື່ອນໄຂການໃຊ້',readVerify:'ອ່ານ ແລະກວດສອບ',browse:'ຄົ້ນໃນຫໍສະໝຸດ',dataProgress:'ຄວາມຄືບໜ້າຂໍ້ມູນ',reportCorrection:'ແຈ້ງຂໍ້ແກ້ໄຂ',integrity:'ຂໍ້ຄວາມພຣະທຳເນັ້ນແຫຼ່ງທີ່ກວດສອບໄດ້ ແລະບໍ່ໃຊ້ AI ສ້າງພຣະສູດຂຶ້ນໃໝ່.',backLibrary:'ຫໍສະໝຸດ',mp3Available:'ມີ MP3',listenDownload:'ຟັງ ແລະດາວໂຫຼດ',listenLabel:'ຟັງ',listenSub:'MP3 ຈັດເຮັດແລ້ວ · ທຸກອຸປະກອນ',openDownloadMp3:'ເປີດ / ດາວໂຫຼດ MP3',textSource:'ແຫຼ່ງຂໍ້ຄວາມ',pdfGenerate:'ສ້າງ PDF ຈາກຂໍ້ຄວາມນີ້',pdfGenerated:'ສ້າງແລ້ວ',fullText:'ເນື້ອຫາເຕັມ',readHere:'ອ່ານເຕັມໃນຫໍສະໝຸດ',translation:'ຄຳແປ',source:'ແຫຼ່ງທີ່ມາ',verifySource:'ກວດສອບແຫຼ່ງ',unavailable:'ຍັງບໍ່ມີຄຳແປທີ່ເຊື່ອຖືໄດ້ສຳລັບພາສານີ້ ຫຼືແຫຼ່ງຂໍ້ມູນບໍ່ພ້ອມຊົ່ວຄາວ.',fallbackTitle:'ສະແດງພາສາອັງກິດຊົ່ວຄາວ',fallbackBody:'ຍັງບໍ່ມີຄຳແປທີ່ມີແຫຼ່ງອ້າງອີງເຊື່ອຖືໄດ້ສຳລັບພາສາທີ່ເລືອກ ຈຶ່ງສະແດງຄຳແປອັງກິດຊົ່ວຄາວ ພ້ອມລະບຸແຫຼ່ງ ແລະຜູ້ແປ.',moreCollection:'ອ່ານຕໍ່ໃນນິກາຍນີ້',minutes:'ນາທີ',passageCollection:'ຊຸດຂໍ້ຄວາມທີ່ບັນທຶກ',savedCount:'ບັນທຶກແລ້ວ',copy:'ສຳເນົາ',save:'ບັນທຶກ'},
  zh:{brand:'巴利三藏图书馆',brandSub:'经藏 · 律藏 · 论藏 · 上座部',primaryNav:'主导航',mobileNav:'移动导航',home:'首页',collections:'五部尼柯耶',canon:'巴利三藏',library:'查找经文',listen:'聆听',progress:'图书馆进度',search:'搜索',footerDescription:'用于阅读、聆听和保存尼柯耶、律藏与论藏的数字图书馆，并保留可核查的来源信息。',libraryInfo:'图书馆',about:'关于',editorial:'来源与编辑原则',privacy:'隐私',terms:'使用条款',readVerify:'阅读与核查',browse:'浏览经库',dataProgress:'数据进度',reportCorrection:'报告勘误',integrity:'经文优先采用可核查来源；不会使用 AI 编造经文。',backLibrary:'经库',mp3Available:'有 MP3',listenDownload:'聆听与下载',listenLabel:'聆听',listenSub:'预生成 MP3 · 所有设备',openDownloadMp3:'打开 / 下载 MP3',textSource:'文本来源',pdfGenerate:'从当前经文生成 PDF',pdfGenerated:'已生成',fullText:'全文',readHere:'在本馆阅读全文',translation:'译文',source:'来源',verifySource:'核对来源',unavailable:'当前语言的可靠译文尚不可用，或来源暂时无法读取。',fallbackTitle:'暂时显示英文译文',fallbackBody:'所选语言暂时没有可追溯来源的可靠译文，因此清楚标示并暂时显示英文译文，同时保留来源与译者信息。',moreCollection:'同部经文继续阅读',minutes:'分钟阅读',passageCollection:'经文摘录',savedCount:'已保存',copy:'复制',save:'保存'}
};

export function publicUi(locale:Locale):Copy{
  return copies[(locale in copies?locale:'en') as PublicLocale];
}
