import Link from 'next/link';
import {BookOpen, Headphones, Bookmark, Play, ArrowRight} from 'lucide-react';
import {dict,isLocale,type Locale} from '@/lib/i18n';
import {collections} from '@/lib/data';
import LibraryExplorer from '@/components/LibraryExplorer';
import {notFound} from 'next/navigation';
export default async function LocaleHome({params}:{params:Promise<{locale:string}>}){const p=await params;if(!isLocale(p.locale))notFound();const locale=p.locale as Locale;const d=dict(locale);const vi=locale==='vi';return <main>
<section className="shell hero"><div><div className="eyebrow">{d.heroEyebrow}</div><h1>{d.heroTitle}</h1><p className="lede">{d.heroLead}</p><div className="heroActions"><a className="btn btnPrimary" href="#library"><BookOpen size={18}/>{d.explore}</a><Link className="btn" href={`/${locale}/library/mn-21-kakacupama`}>{d.continue}<ArrowRight size={17}/></Link></div></div><aside className="heroCard"><div className="quote"><p>“Sabbe saṅkhārā aniccā.”</p><small>Dhammapada 277 · “All conditioned things are impermanent.”</small></div><div className="metrics"><div className="metric"><strong>5</strong><span>Nikāyas</span></div><div className="metric"><strong>16</strong><span>UI languages</span></div><div className="metric"><strong>PDF · MP3</strong><span>download-ready</span></div></div></aside></section>
<section className="section" id="collections"><div className="shell"><div className="sectionHead"><div><h2>{d.collections}</h2><p>{d.collectionsLead}</p></div></div><div className="cards">{collections.map(c=><article className="collection" key={c.code}><span className="code">{c.code}</span><h3>{vi?c.vi:c.en}</h3><p><em>{c.pali}</em><br/>{vi?c.descVi:c.descEn}</p><div className="count">{c.count}</div></article>)}</div></div></section>
<section className="section" id="listen"><div className="shell"><div className="sectionHead"><div><h2>{d.features}</h2><p>{d.featuresLead}</p></div></div><div className="featureGrid"><div className="feature"><span className="featureIcon"><BookOpen/></span><h3>{d.fRead}</h3><p>{d.fReadD}</p></div><div className="feature"><span className="featureIcon"><Headphones/></span><h3>{d.fAudio}</h3><p>{d.fAudioD}</p></div><div className="feature"><span className="featureIcon"><Bookmark/></span><h3>{d.fProgress}</h3><p>{d.fProgressD}</p></div></div></div></section>
<section className="section"><div className="shell mediaPanel"><div className="copy"><div className="eyebrow" style={{color:'#e6bd79'}}>{d.videoCta}</div><h2 style={{fontFamily:'Georgia,serif',fontSize:34}}>{d.videoTitle}</h2><p>{d.videoBody}</p><span className="btn" style={{marginTop:8}}><Play size={17}/> YouTube module</span></div><div className="videoMock" aria-label="YouTube integration preview"><span className="play"><Play size={28} fill="currentColor"/></span></div></div></section>
<section className="section" id="library"><div className="shell"><LibraryExplorer locale={locale} placeholder={d.search}/></div></section>
<footer><div className="shell">{d.footer}</div></footer></main>}
