#!/usr/bin/env python3
"""Generate static imports so Next.js bundles every materialized corpus shard."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "data/content"
TARGET = ROOT / "lib/materialized-content.generated.ts"


def main() -> None:
    paths = sorted(CONTENT.glob("*.vi.json"))
    for directory in sorted(p for p in CONTENT.iterdir() if p.is_dir()):
        paths.extend(sorted(directory.glob("*.vi.json")))
    imports = []
    names = []
    for index, path in enumerate(paths):
        name = f"corpus{index}"
        rel = path.relative_to(ROOT).as_posix()
        imports.append(f"import {name} from '@/" + rel + "';")
        names.append(name)
    lines = ["// Generated by scripts/generate_content_registry.py; do not edit by hand.", *imports, "", "export const materializedVi:Record<string,unknown>=Object.assign({}, " + ", ".join(names) + ");", ""]
    TARGET.write_text("\n".join(lines), encoding="utf-8")
    print(f"Generated {TARGET.relative_to(ROOT)} with {len(paths)} corpus shards")


if __name__ == "__main__":
    main()
