#!/usr/bin/env python3
"""Generate server full-text registry plus a lightweight public scripture catalog."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "data/content"
FULL_TARGET = ROOT / "lib/materialized-content.generated.ts"
CATALOG_TARGET = ROOT / "lib/materialized-catalog.generated.ts"


def corpus_paths() -> list[Path]:
    paths = sorted(CONTENT.glob("*.vi.json"))
    for directory in sorted(p for p in CONTENT.iterdir() if p.is_dir()):
        paths.extend(sorted(directory.glob("*.vi.json")))
    return paths


def clean_title(value: str, ref: str) -> str:
    value = re.sub(rf"^{re.escape(ref)}\.?\s*", "", value, flags=re.I)
    value = re.sub(r"^\d+(?:\.\d+)*\.?\s*", "", value).strip()
    return value or f"Bài kinh {ref.upper()}"


def derive_title(entry: dict, ref: str) -> str:
    texts = [str(s.get("text", "")).strip() for s in entry.get("segments", []) if str(s.get("text", "")).strip()]
    specific = next((t for t in texts if re.match(r"^\d+(?:\.\d+)+\.?\s+\S", t)), None)
    if not specific:
        specific = next((t for t in texts if ref.lower() in t.lower()), None)
    specific = specific or (texts[2] if len(texts) > 2 else (texts[0] if texts else ""))
    return clean_title(specific, ref)


def estimate_minutes(entry: dict) -> int:
    words = sum(len(str(s.get("text", "")).split()) for s in entry.get("segments", []))
    return max(1, (words + 199) // 200) if words else 0


def main() -> None:
    paths = corpus_paths()

    imports: list[str] = []
    names: list[str] = []
    lightweight: dict[str, dict] = {}

    for index, path in enumerate(paths):
        name = f"corpus{index}"
        rel = path.relative_to(ROOT).as_posix()
        imports.append(f"import {name} from '@/" + rel + "';")
        names.append(name)

        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, dict):
            continue
        for key, raw in data.items():
            if not isinstance(raw, dict):
                continue
            ref = str(raw.get("canonicalRef") or key).lower()
            collection = str(raw.get("collection") or re.match(r"^[a-z]+", ref).group(0) if re.match(r"^[a-z]+", ref) else "").upper()
            lightweight[ref] = {
                "canonicalRef": ref,
                "collection": collection,
                "titleVi": derive_title(raw, ref),
                "sourceUrl": str(raw.get("sourceUrl") or f"https://suttacentral.net/{ref}/vi/minh_chau"),
                "author": str(raw.get("author") or "Bản dịch nguồn"),
                "license": str(raw.get("license") or "Xem ghi chú quyền sử dụng tại nguồn"),
                "readMinutes": estimate_minutes(raw),
                "contentVersion": str(raw.get("contentVersion") or raw.get("materializedAt") or "materialized-v1"),
            }

    full_lines = [
        "// Generated by scripts/generate_content_registry.py; do not edit by hand.",
        *imports,
        "",
        "export const materializedVi:Record<string,unknown>=Object.assign({}, " + ", ".join(names) + ");",
        "",
    ]
    FULL_TARGET.write_text("\n".join(full_lines), encoding="utf-8")

    payload = json.dumps(lightweight, ensure_ascii=False, separators=(",", ":"))
    CATALOG_TARGET.write_text(
        "// Generated by scripts/generate_content_registry.py; do not edit by hand.\n"
        f"export const materializedCatalog={payload} as const;\n",
        encoding="utf-8",
    )
    print(f"Generated {FULL_TARGET.relative_to(ROOT)} with {len(paths)} corpus shards")
    print(f"Generated {CATALOG_TARGET.relative_to(ROOT)} with {len(lightweight)} lightweight entries")


if __name__ == "__main__":
    main()
